// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
Ads_Build='00000078-2';var QQbA,QQcA,QQdA,QQeA,QQfA,QQgA,QQhA,QQiA,QQjA,QQkA,QQlA,QQmA,QQnA,QQoA,QQpA;NUM_FARM=1;QQbA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQcA=['https://s.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQdA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQeA=['https://s.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQfA=['http://bw.as-test.falkag.net' ,'http://bw.as-eu.falkag.net' ,'http://bw.ads.t-online.de' ,'http://bw.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQgA=['http://bw.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQhA=['http://red.as-test.falkag.net' ,'http://red.as-eu.falkag.net' ,'http://red.ads.t-online.de' ,'http://red.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQiA=['https://red.as-test.falkag.net' ,'https://red.as-eu.falkag.net' ,'https://red.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQjA=['http://sel.as-test.falkag.net/server/asldata.js','http://data.as-eu.falkag.net/server/asldata.js','http://data.ads.t-online.de/server/asldata.js' ,'http://data.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQkA=['https://sel.as-test.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js' ,'https://red.ads.t-online.de/server/asldata.js' ,'https://s.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQlA=['.as-test.falkag.net' ,'.as-eu.falkag.net' ,'.ads.t-online.de' ,'.as-us.falkag.net' ,'.as-rh4.falkag.net' ,'','','','',''];QQmA=['Falk AdSolution' ,'AdSolution' ,'Adsolution' ,'Falk AdSolution' ,'Falk AdSolution RH4' ,'','','','',''];QQnA=['/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'','','','',''];QQoA=['/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'','','','',''];QQpA=['/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'','','','',''];// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
function QQkD(QQRc)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+QQRc+'"></scr'+'ipt>');}function QQlD(QQSc)
{var QQTc=this.location.hostname.toLowerCase();var QQUc='';var QQVc=QQTc;var QQWc=[];QQLc1=QQTc.indexOf('.');if (QQSc==1)
{if (QQLc1!=-1)
{while (QQLc1!=-1)
{QQLc1=QQVc.indexOf('.');QQWc[QQWc.length]=(QQLc1==-1)?QQVc.substring(QQLc1+1,QQVc.length):QQVc.substring(0,QQLc1);QQVc=QQVc.substring(QQLc1+1,QQVc.length);}if (QQWc[QQWc.length-2]=='falkag')
{for (var QQHc=1;QQHc<QQWc.length;QQHc++)
{QQl=QQWc.length-QQHc;QQUc=QQWc[QQl]+((QQUc=='')?'':'.'+QQUc);}}else
{QQUc=(QQWc[QQWc.length-2].length<3)?QQTc:QQWc[QQWc.length-2]+'.'+QQWc[QQWc.length-1];}}}else
{if (QQLc1==-1)
{QQUc='';}else
{if((QQLc1>=0)&&(QQLc1<QQTc.length))
{QQLc2=QQTc.indexOf('.',QQLc1+1);if(QQLc2>QQLc1)
QQUc=QQTc.substring(QQLc1+1,QQTc.length);}if ((QQUc.lastIndexOf('.')==QQUc.indexOf('.'))&&QQUc.lastIndexOf('.')<3)
QQUc=QQTc;}}return QQUc;}function QQmD()
{var QQUc=QQlD(0);if(QQUc=='')
return 'D'+this.location.hostname;else
return 'D'+QQUc;}function QQnD(QQXc)
{var QQUc=QQlD(0);if(QQXc==-1)
{	 if(QQUc!='')
	 QQUc=';domain='+QQUc;	return ';path=/;'+QQUc;}if(QQXc==-2)
{	 if(QQUc!='')
	 QQUc=';domain='+QQUc
			return ';path=/;expires=Thu,01-Jan-1970 00:00:01 GMT'+QQUc;		}var QQYc=new Date();if(QQUc!='')
QQUc=';domain='+QQUc;QQYc.setTime(parseInt(QQYc.getTime(),10)+1000*60*parseInt(QQXc,10));return ';path=/;expires='+QQYc.toGMTString()+QQUc;}function QQoD(QQXc)
{var QQUc=QQlD(1);if(QQXc==-1)
{	 if(QQUc!='')
	 QQUc=';domain='+QQUc;	return ';path=/;'+QQUc;}var QQYc=new Date();if(QQUc!='')
QQUc=';domain='+QQUc;QQYc.setTime(parseInt(QQYc.getTime(),10)+1000*60*parseInt(QQXc,10));return ';path=/;expires='+QQYc.toGMTString()+QQUc;}function QQpD(QQc,QQd,QQy)
{if(QQsA!=-1) var intBwdTyp=KAS[QQsA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var QQz=[];		
		QQcD( Ads_iid,QQc)
		
		QQyD(1,'HAAAALLO!!!!',QQc);		
QQz[0]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+QQy[0]+((QQcD( Ads_iid,QQc )&&(QQvB>0))?QQtB:'');QQz[1]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+'&chw='+QQqA+'&tcs='+QQrA+QQy[1]+((QQcD( Ads_iid,QQc )&&(QQvB>0))?QQtB:'')+QQvA;var QQZc='&sta=';QQz[0]+='&dmn='+Ads_T[5];QQz[1]+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{QQz[0]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQz[1]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQZc+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
QQz[1]+='&jav=1';}else
QQZc+=',,,';var QQAd=new Date();QQZc+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{var QQDc='!"%&\'()*+#-./:;<=>?@[\\]^{|}~ï¿½ ';var QQEc,QQBd='';for(QQl=0;QQl<Ads_wrd.length;QQl++)
{QQEc=Ads_wrd.charAt(QQl);if(QQDc.indexOf(QQEc)!=-1)
QQEc=',';QQBd+=QQEc;}QQBd =QQBd.toLowerCase();QQz[0]+='&wrd='+QQBd;QQz[1]+='&wrd='+QQBd;Ads_wrd=QQBd;QQZc+='';}QQZc+=','+QQfF[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];QQz[0]+=QQZc;QQz[1]+=QQZc;if(gbolSUXX25067) QQz[1]+='&trglog='+escape(gstrXarrTargetDaten);QQz[0]=Ads_Timestamp+QQz[0];QQz[1]=Ads_Timestamp+QQz[1];QQz[2]=QQz[1]+QQy[0];return (QQz);}function QQqD(QQc,QQd,QQy)
{var QQCd=[];var QQPc=[];QQPc=QQpD(QQc,QQd,QQy);QQCd[0] ='&rdm='+QQPc[0]+'&iid='+Ads_iid+'&bid='+QQd;QQCd[1] ='&rdm='+QQPc[1]+'&iid='+Ads_iid+'&bid='+QQd;return QQCd;}function QQrD()
{if (typeof(QQgB[Ads_sec])=='undefined')
QQyC();return QQgB[Ads_sec]+(QQyA?QQoA[NUM_FARM]+'flg='+QQbD()+'&dat='+QQfB[Ads_sec]+'/dat/bgf/trpix.gif&':QQnA[NUM_FARM]);}function QQsD()
{return QQgB[Ads_sec]+QQnA[NUM_FARM]+'cmd=req&';}function QQtD(QQDd,QQb)
{var QQa=(QQDd==0)?QQrD():QQsD();QQyD(1,'Tracking URL (0=>Standard 1=>Request)',QQDd+' ('+QQa+QQb+')');if (QQDd==0)
{return ((Ads_opt&512)>0)?'':(QQcE('Ads_Count'+Ads_iid)+'<img src="'+QQrD()+QQb+'" width="1" height="1">'+QQdE());}else if (QQDd==1)
{return QQcE('Ads_ReqCount'+Ads_iid)+'<img src="'+QQsD()+QQb+'" width="1" height="1">'+QQdE();}}function QQuD(QQt,QQb)
{QQyD(1,'Impression Parameters',QQb);QQt.document.write(QQtD(0,QQb));}function QQvD()
{return QQwD(Math.random()*100000000,8);}function QQwD(QQEd,QQFd)
{var QQGd='#'+(QQEd+100000000);return QQGd.substr(10-QQFd,QQFd);}function QQxD(QQBd,QQHd,QQId)
{var QQl;while((QQl=QQBd.indexOf(QQHd))!=-1)
QQBd=QQBd.substr(0,QQl)+QQId+QQBd.substring(QQl+QQHd.length,QQBd.length);return QQBd;}function QQyD(QQE,QQBd,QQJd)
{var QQKd=new Date();if(Ads_debug==1)
{document.write(((QQE!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((QQKd-QQwA)/1000)+']</font> ');if((QQE==0)||(QQE==3))
document.write('<b><big>'+QQBd+'</big></b><br>');else if(QQE==1)
document.write(''+QQBd+': &nbsp;<font color=#000080>'+QQJd+'</font><br>');else
document.write('<b>'+QQBd+'</b><br>');}else if((Ads_debug==2)&&(QQE==3))
document.write('<font color=#0000ff>[DEBUG'+((QQKd-QQwA)/1000)+']</font> <b><big>'+QQBd+'</big></b><br>');}function QQzD(QQCb)
{var QQD='#'+(parseInt(QQCb,10)+100000000);return QQD.substr(2,2)+'/'+QQD.substr(4,2)+'/'+QQD.substr(6,2)+'/'+QQD.substr(8,2);}function QQaE(QQEd)
{var QQLd='0123456789ABCDEF';var QQMd='';while(QQEd>0)
{QQMd=QQLd.substr(QQEd%16,1)+QQMd;QQEd=parseInt(QQEd/16,10);}return (QQMd=='')?'0':QQMd;}function QQbE(QQMa)
{var QQNd;var QQOd=0;if(QQaB>-1)
{QQOd=QQaB;return QQOd;}if((QQMa==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQNd=navigator.plugins['Shockwave Flash'].description;QQNd=QQNd.substring(QQNd.indexOf("."),-1);QQOd=QQNd.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Mac")!=-1&&document.all)
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQNd=navigator.plugins['Shockwave Flash'].description;QQNd=QQNd.substring(QQNd.indexOf("."),-1);QQNd=QQNd.substring(QQNd.length-1,QQNd.length);QQOd=QQNd.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');QQOd=Ads_vbCV;}QQaB=QQOd;return QQOd;}function QQcE(QQPd)
{if(QQrB)
return '<div id='+QQPd+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function QQdE()
{if(QQrB)
return '</div>';else
return '';}function QQeE(QQQd)
{var QQRd,QQSd;if(window.innerHeight)
{QQRd=QQQd.x;QQSd=QQQd.y;}else
{if(QQQd.offsetLeft)
{QQQd=QQQd;QQRd=QQQd.offsetLeft;QQNk=QQQd.offsetParent;while(QQNk!=null)
{QQRd+=QQNk.offsetLeft;QQNk=QQNk.offsetParent;}QQSd=QQQd.offsetTop;QQNk=QQQd.offsetParent;while(QQNk!=null)
{QQSd+=QQNk.offsetTop;QQNk=QQNk.offsetParent;}}else
return [-1000,-1000];}return [QQRd,QQSd];}function QQfE(QQTd,QQA,QQf,QQg)
{var QQUd;var QQQd=document.images[QQA];var QQVd=QQeE(QQQd);QQQd.width=QQf;QQQd.height=QQg;if(QQrB)
QQUd=document.getElementById(QQTd).style;else if(document.layers)
QQUd=document.layers[QQTd];else
QQUd=document.all[QQTd].style;QQUd.left=QQVd[0];QQUd.top=QQVd[1];if (QQrB) QQUd.display='block';else if(document.layers) QQUd.visibility='show';else QQUd.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQaD;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var QQqA,QQrA,QQsA,QQtA,QQuA,QQvA,QQwA,QQxA;var QQyA,QQzA,QQaB,QQbB,QQcB,QQdB;var QQeB=false;var QQfB=[];var QQgB=[];var QQhB=[];var QQiB=[];var QQjB=[];var QQkB=[];var QQlB=[];var QQmB=navigator.userAgent.toLowerCase();var QQnB=(QQmB.indexOf("msie")!=-1);var QQoB=((QQmB.indexOf("win")!=-1)||(QQmB.indexOf("16bit")!=-1));var QQpB=(QQmB.indexOf("mac")!=-1);var QQqB=(navigator.appName.indexOf('icrosoft')!=-1);var QQrB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var QQsB=true;var QQtB='';var QQuB='';var QQvB=0;var QQwB=[];var QQxB=0;var QQyB=0;var QQzB=[];var QQaC;var QQbC=[];var QQcC=[];var QQdC=[];var QQeC=[];var QQfC=[];var QQgC=[];var QQhC=[];var QQiC=[];var Ads_LinkUrl,Ads_CountUrl,Ads_LinkAltUrl,Ads_CountAltUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,Ads_T_OW,iid,bid,rdm;var Ads_Data=[];var Ads_status=[];var QQjC=0;if(typeof(Ads_FXPL)=='undefined'){var Ads_FXPL=false;}Ads_T_OW=[];var QQkC=false;var QQlC=0;var QQmC=0;var QQnC,QQoC,Ads_gintCurVersion;var QQpC='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(QQnC,'flashwin',QQpC);}function emosite(){window.open(QQnC,'flashwin',QQpC);}function FlashClick(){window.open(QQnC,'flashwin',QQpC);}function link1(){window.open(QQnC,'flashwin',QQpC);}function gotoURL(QQa){window.open(QQoC+escape(QQa),'flashwin',QQpC);}function QQqC()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function QQrC(QQa)
{QQa=QQxD(QQa,'[par]',escape(Ads_par));QQa=QQxD(QQa,'[keyword]',escape(Ads_wrd));QQa=QQxD(QQa,'[timestamp]',Ads_Timestamp);if (typeof(Ads_CountUrl)!='undefined')
{QQa=QQxD(QQa,'[clickurl]',escape(Ads_CountUrl));QQa=QQxD(QQa,'[clickurl_plain]',Ads_CountUrl);QQa=QQxD(QQa,'[clickurl_double]',escape(escape(Ads_CountUrl)));QQa=QQxD(QQa,'[clickurl_ne]',escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne='));QQa=QQxD(QQa,'[clickurl_plain_ne]',Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=');QQa=QQxD(QQa,'[clickurl_double_ne]',escape(escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=')));}QQa=QQxD(QQa,'[web_id]',Ads_wid);QQa=QQxD(QQa,'[web_external_id]',escape(Ads_xwid));QQa=QQxD(QQa,'[con_id]',Ads_iid);QQa=QQxD(QQa,'[con_external_id]',escape(Ads_xiid));QQa=QQxD(QQa,'[ban_id]',Ads_sbid);QQa=QQxD(QQa,'[cam_id]',QQtA);return QQa;}function QQsC(QQa,QQb)
{return QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQbD()+'&'+QQb+'&dat='+escape(QQa);}function QQtC(QQc,QQd,QQe,QQf,QQg)
{var QQh;if(QQvB<2)
{QQvB++;QQh=QQvB+1;QQtB+='&kid'+QQh+'='+QQc;QQtB+='&bid'+QQh+'='+QQd;QQtB+='&iid'+QQh+'='+Ads_iid;QQtB+='&dlv'+QQh+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd;if(QQuA!=0)
QQtB+='&sid'+QQh+'='+QQuA;QQtB+='&bls3'+QQh+'='+QQuB;arrIntern=QQeD(QQe);Ads_iid=arrIntern[1];Ads_kid=(arrIntern.length<3||typeof(arrIntern[2])=='undefined')?0:arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xp=(arrIntern.length<6||Ads_xp!='')?Ads_xp:arrIntern[5];Ads_yp=(arrIntern.length<7||Ads_yp!='')?Ads_yp:arrIntern[6];Ads_xp1=(arrIntern.length<8||Ads_xp1!='')?Ads_xp1:arrIntern[7];Ads_yp1=(arrIntern.length<9||Ads_yp1!='')?Ads_yp1:arrIntern[8];QQxB=Ads_iid;QQyB=Ads_kid;				
Ads_xl=0;Ads_yl=0;QQkD(QQfB[Ads_sec]+'/dat/cjf/'+QQzD(Ads_iid)+'.js');}else
{QQtB='';QQvB=0;QQqC();}}function QQuC(QQi)
{var QQj=[];var QQk=QQi.length;var QQl;var QQm='';var QQn='';for(QQl=0;QQl<QQk;QQl+=2)
{QQm=QQi[QQl+1];/*
if(Ads_cnturl!='')
{QQn=QQxD(Ads_cnturl,'[url]',escape(QQm));QQm=QQxD(QQn,'[url_plain]',QQm);}*/
QQj[QQl/2+1]=Ads_CountUrl+escape(QQm)+'&bidx='+QQi[QQl];}return QQj;}function SAS()
{var QQo=false;QQyC();QQo=QQzC();	
	
	if (typeof(IAS[18])=='undefined')
		IAS[18]=0;	if (Ads_farmid==2)
		IAS[18]=1;		
	
if (QQo==true)
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
QQeF();else
QQvC();}else
{QQsB=false;QQyD(1,'Waiting for asldata.','');}}function QQvC()
{var QQp;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQaD;if(((Ads_nid==631)||(Ads_nid==668))&&(NUM_FARM==1))
{ QQfB[0]=['http://e.as-eu.falkag.net'];QQiB[0]=QQfB[0];}if((Ads_nid==80)&&(NUM_FARM==3))
{ QQfB[0]=['http://e.as-us.falkag.net'];QQiB[0]=QQfB[0];}var QQq='undefined';for (QQHc=0;QQHc<Ads_T.length;QQHc++)
{if (typeof(Ads_T_OW)!=QQq)
{if (typeof(Ads_T_OW[QQHc])!=QQq)
{QQyD(1,'Overwriting Targeting AdsT['+QQHc+'] ('+Ads_T[QQHc]+') with',Ads_T_OW[QQHc]);Ads_T[QQHc]=Ads_T_OW[QQHc];}}}if(typeof(Ads_cmd)==QQq) Ads_cmd='';if(typeof(Ads_kid)==QQq) Ads_kid=0;if(typeof(Ads_bid)==QQq) Ads_bid=0;if(typeof(Ads_xl)==QQq) Ads_xl=0;if(typeof(Ads_yl)==QQq) Ads_yl=0;if(typeof(Ads_xp)==QQq) Ads_xp='';if(typeof(Ads_yp)==QQq) Ads_yp='';if(typeof(Ads_xp1)==QQq) Ads_xp1='';if(typeof(Ads_yp1)==QQq) Ads_yp1='';if(typeof(Ads_opt)==QQq) Ads_opt=0;if(typeof(Ads_wrd)==QQq) Ads_wrd='';if(typeof(Ads_prf)==QQq) Ads_prf='';if(typeof(Ads_par)==QQq) Ads_par='';if(typeof(Ads_cnturl)==QQq) Ads_cnturl='';if(typeof(Ads_ref)==QQq) Ads_ref=0;if(typeof(Ads_anc)==QQq) Ads_anc='';if(typeof(Ads_cmb)==QQq) Ads_cmb=[];if(typeof(Ads_uid)==QQq) Ads_uid='';if(typeof(Ads_bgc)==QQq) Ads_bgc='';if(typeof(Ads_status[Ads_iid])==QQq) Ads_status[Ads_iid]=[3,0,0,1];Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=QQq)
Ads_bgc=IAS[16];}QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref +'&xp1='+Ads_xp1+'&yp1='+Ads_yp1+'&opt=';var QQr='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+QQp+Ads_opt+QQr);Ads_ref=0;return;}QQoF();if((Ads_bgc!='')&&(Ads_bgc!='-1')&&(document.body!=null))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(QQfF[10]==0))
QQbF();QQqA='';QQrA='';QQtA=0;QQuA=0;QQvA='';QQsA=-1;if(NUM_FARM==3)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];if((Ads_kid==0)||(Ads_kid==''))
QQsA=QQjE();else
{QQk=KAS.length;QQsA=0;while((QQsA<QQk)&&(KAS[QQsA][0]!=Ads_kid))
QQsA++;if(QQsA==QQk)
QQsA=-1;}if((Ads_opt&256)!=0)
{if(QQsA!=-1)
{Ads_skid=KAS[QQsA][0];Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=4;}else
Ads_skid=0;QQyD(1,'Skipping delivery,selected campaign:',Ads_skid);}else
{if(QQsA!=-1)
{QQtA=KAS[QQsA][0];QQuA=KAS[QQsA][6];if(QQuA!=0)
QQvA='&sid='+QQuA;Ads_status[Ads_iid][0]=(KAS[QQsA][2]==0)?2:1;Ads_status[Ads_iid][3]=3;if(QQtA>0)
{QQkD(QQfB[Ads_sec]+'/dat/bjf/'+QQzD(QQtA)+'.js');}else
DAS();}else
{QQyD(1,'no campaign selected!','');if (Ads_nid!=0)
Ads_status[Ads_iid][3]=2;DAS();}}}function DAS()
{var QQs,QQk,QQt,QQu,QQv,QQw,QQx,QQy,QQz;QQy=['',''];QQz=[];var QQA='';var QQB=['_blank','_self','_parent','_top'];var QQC=false;Ads_Timestamp=QQvD();var QQd=0;var QQD,QQf,QQg;if(IAS[9]==1)
{QQD='adsolut.gif';QQf=234;QQg=60;}else
{QQD='trpix.gif';QQf=1;QQg=1;}QQbB=QQmA[NUM_FARM];if(IAS[9]==4)
QQbB='Werbung';if (NUM_FARM==2){QQbB='onmouseover="self.status=\'\';return true;" ';}else{QQbB='onmouseover="self.status=\''+QQbB+'\';return true;" ';}if(IAS[9]==5)
QQbB='';var QQE=1;var QQa='http://www.falkag.de';// Ziel-Url
var QQF=(NUM_FARM==2)?'':'Falk AdSolution';var QQG=0;var QQH='';var QQI='';var QQJ='';var QQK='';var QQL='';var QQM=0;var QQN=0;var QQO=0;var QQP=0;var QQQ=1;var QQR=2;var QQe='';var QQS='';var QQi=[];var QQT=0;var QQU='';var QQV='';var QQW=false;var QQX=0;var QQY=false;var QQZ,QQAa,QQBa,QQCa,QQDa,QQEa,QQFa,QQGa,QQHa,QQIa;if(QQtA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
QQs=QQkE(QQsA,QQtA);else
{QQk=BAS.length;QQs=0;while((BAS[QQs][0]!=Ads_bid)&&(QQs<QQk))
QQs++;if(QQs==QQk)
QQs=-1;}if(QQs!=-1)
QQd=BAS[QQs][0];}if(QQd>0)
{QQE=BAS[QQs][3];QQD=BAS[QQs][4];QQa=BAS[QQs][5];QQF=BAS[QQs][6];QQG=BAS[QQs][12];QQH=BAS[QQs][7];QQI=BAS[QQs][8];QQJ=BAS[QQs][9];QQK=BAS[QQs][10];QQL=BAS[QQs][11];QQf=BAS[QQs][13];QQg=BAS[QQs][14];QQM=BAS[QQs][15];QQN=BAS[QQs][16];QQQ=BAS[QQs][17];QQR=BAS[QQs][18];QQe=BAS[QQs][19];QQS=BAS[QQs][20];QQi=BAS[QQs][22];QQT=BAS[QQs][23];QQU=BAS[QQs][24];QQV=BAS[QQs][25];QQX=BAS[QQs][27];if (!QQeB)
QQeB=(BAS[QQs][26]==1);Ads_klist+=QQtA+'#';QQv=KAS[QQsA][4][25];if(QQv>0)
{if(typeof(Ads_fcount[QQv])=='undefined')
Ads_fcount[QQv]=1;else
Ads_fcount[QQv] ++;}}if(QQtA==-1)
{QQtA=99999999;QQd=99999999;QQC=true;}Ads_skid=QQtA;Ads_sbid=QQd;QQI=(QQI=='')?QQa:QQI;QQZ=(QQG&24);QQAa=QQB[QQG&3];QQDa=((QQG&64)>0)&&((Ads_opt&64)==0);QQBa=(QQG&128)>0;QQCa=(QQG&512)>0;QQW=(QQU=='_search')||(QQU=='_media');QQEa=((QQG&1024)>0)&&Ads_ModulEffects;QQFa=((QQG&8192)>0);QQTk=((Ads_opt&2)>0)&&!QQC&&(QQd!=0);QQGa=(QQG&2048)>0;QQHa=(QQS.length>0);QQY=(QQX==0)?false:true;QQf=(Ads_xl>0)?Ads_xl:QQf;QQg=(Ads_yl>0)?Ads_yl:QQg;QQM=(Ads_xp!='')?Ads_xp:QQM;QQN=(Ads_yp!='')?Ads_yp:QQN;QQO=(Ads_xp1!='')?Ads_xp1:QQO;QQP=(Ads_yp1!='')?Ads_yp1:QQP;QQyA=(QQG&4096)>0;Ads_opt|=(QQG&16384)>0?64:0;Ads_opt|=IAS[3]*32;if(QQwB.length!=0)
{QQqA+=QQwB[13];QQrA+=QQwB[14];}if (!QQTk||(QQTk&&(QQC==true||(Ads_cmd =='win'))))
{if(QQtA>0&&QQC==false&&QQsA!=-1)
QQy=QQrF(QQtA,QQsA,QQd,QQs,((QQG&4096)>0));QQz=QQqD(QQtA,QQd,QQy);QQyD(1,'Count-String [Click/Impression]',QQz[0]+'/'+QQz[1]);}if (QQY&&Ads_cmd!='win')
{var QQJa='nid='+Ads_nid+'&iid='+Ads_iid+'&bid='+QQd+'&rdm='+QQvD();document.write(QQtD(1,QQJa));}if(Ads_anc!='')
{QQw=true;QQA=Ads_anc;Ads_anc='';}QQa=QQrC(QQa);QQI=QQrC(QQI);/*
if(Ads_cnturl!='')
{QQIa=QQxD(Ads_cnturl,'[url]',escape(QQa));QQa=QQxD(QQIa,'[url_plain]',QQa);QQIa=QQxD(Ads_cnturl,'[url]',escape(QQI));QQI=QQxD(QQIa,'[url_plain]',QQI);}if((QQE==3)||(QQE==4)||(QQE==8))
{Ads_LinkUrl=QQa;Ads_CountUrl=QQsC('',QQz[0]);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(QQa);Ads_MultiUrl=QQuC(QQi);Ads_ViewCode=QQtD(0,QQz[1]);Ads_ViewUrl=QQrD()+QQz[1];}*/
Ads_LinkUrl=QQa;Ads_LinkAltUrl=QQI;Ads_CountUrl=QQsC('',QQz[0]);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';if(Ads_cnturl!=''&&(Ads_cnturl.indexOf('[url]')!=-1||Ads_cnturl.indexOf('[url_plain]')!=-1||Ads_cnturl.indexOf('[url_double]')!=-1))
{QQDm=QQxD(Ads_cnturl,'[url]',escape(Ads_CountUrl));QQDm=(QQE==4)?QQxD(QQDm,'[url_double]',escape(escape(Ads_CountUrl))):QQxD(QQDm,'[url_double]',escape(Ads_CountUrl));QQEm=QQxD(QQDm,'[url_plain]',Ads_CountUrl);QQDm=QQxD(Ads_cnturl,'[url]',escape(Ads_CountUrl_ne));QQDm=(QQE==4)?QQxD(QQDm,'[url_double]',escape(escape(Ads_CountUrl_ne))):QQxD(QQDm,'[url_double]',escape(Ads_CountUrl_ne));QQFm=QQxD(QQDm,'[url_plain]',Ads_CountUrl_ne);Ads_CountUrl=QQEm;Ads_CountUrl_ne=QQFm;QQyD(1,'Ads_CountUrl',Ads_CountUrl);QQyD(1,'Ads_CountUrl_ne',Ads_CountUrl_ne);}Ads_ClickUrl=Ads_CountUrl+escape(Ads_LinkUrl);Ads_ClickAltUrl=Ads_CountUrl+escape(Ads_LinkAltUrl);Ads_MultiUrl=QQuC(QQi);Ads_ViewCode=QQtD(0,QQz[1]);Ads_ViewUrl=QQrD()+QQz[1];QQyD(1,'Ads_CountUrl',Ads_CountUrl);if(QQE==1)
QQJ=QQiB[Ads_sec]+'/dat/bgf/'+QQD;if(QQwB.length!=0)
{if(!QQBa)
{QQBa=QQwB[0];QQDa=QQwB[1];QQCa=QQwB[2];QQR=QQwB[3];QQEa=QQwB[4];QQFa=QQwB[5];}if(!QQHa)
{QQHa=QQwB[6];QQS=QQwB[7];}QQM=QQwB[8];QQN=QQwB[9];QQO=QQwB[16];QQP=QQwB[17];QQZ=QQwB[10];IAS[2]=QQwB[11];IAS[11]=QQwB[12];QQA=QQwB[15];QQw=(QQA!='');QQwB=[];}if(QQE==5)
{QQwB=[QQBa,QQDa,QQCa,QQR,QQEa,QQFa,QQHa,QQS,QQM,QQN,QQZ,IAS[2],IAS[11],QQqA,QQrA,QQA,QQO,QQP];QQBa=false;QQHa=false;QQw=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(QQE!=5))
{self.location.href=QQsC(QQa,QQz[0]);QQBa=false;QQHa=false;QQw=false;QQE=6;return;}if(QQBa&&!QQW)
{if (!QQTk)
QQt=QQvI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'');else
QQt=window;if(QQDa)
{if(window.innerHeight)
{QQf=QQt.innerWidth;QQg=QQt.innerHeight;}else
{QQf=QQt.document.body.clientWidth;QQg=QQt.document.body.clientHeight;}}if (!QQTk||(QQTk&&Ads_cmd=='win'))
if(QQCa&&(QQR==0))
QQt.blur();else if(QQCa)
QQt.setTimeout('window.blur();',QQR*1000);}else
QQt=window;if(QQw)
document.write(QQcE('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&QQHa)
{if(QQZ==16)
QQZ=1;else if(QQZ==24)
QQZ=2;else
QQZ=0;QQcI(Ads_iid,QQf,QQg,QQM,QQN,QQZ,QQS,QQBa,QQt);QQdI(Ads_iid,Ads_sec);}QQyD(1,'Banner-Typ/PopUp',QQE+'/'+QQBa);var QQKa='';if (QQTk&&QQtA>0)
QQKa='QQy=QQrF('+QQtA+','+QQsA+','+QQd+','+QQs+','+((QQG&4096)>0)+');';QQxI(QQtA,QQd,QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'',QQTk,QQKa);if (!QQC&&QQd==0&&QQtA)
{Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=3;}else if (QQC)
{Ads_status[Ads_iid][0]=3;Ads_status[Ads_iid][3]=2;}else if (!QQC&&QQd>0)
{Ads_status[Ads_iid][1]=QQf;Ads_status[Ads_iid][2]=QQg;Ads_status[Ads_iid][3]=0;}if (!QQTk||(QQTk&&(Ads_cmd =='win')))
{if(QQE<2)
QQpI(QQt,QQBa,QQz,QQJ,QQa,QQAa,QQf,QQg,QQF,QQW,QQU,QQd,QQM,QQN);else if(QQE==2)
QQqI(QQt,QQBa,QQz,QQD,QQa,QQAa,QQf,QQg,QQF,QQH,QQI,QQGa,QQQ,QQV);else if(QQE==3)
QQrI(QQt,QQBa,QQz,QQtA,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,'/dat/brf/',0,QQW,QQTk,QQE);else if(QQE==4)
QQsI(QQt,QQBa,QQz,QQK,QQL,QQHa,QQf,QQg,QQw);else if(QQE==5)
QQtC(QQtA,QQd,QQe,QQf,QQg);else if(QQE==8)
QQrI(QQt,QQBa,QQz,QQtA,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,'/dat/bfx/',parseInt(QQe,10),QQW,QQTk);}QQyD(3,'Banner-display finished');QQcF();if(QQw)
{document.write(QQdE());setInterval('QQfE("Ads_place'+Ads_iid+'","'+QQA+'",'+QQf+','+QQg+');',20);}if(Ads_ModulEffects&&QQHa)
QQeI(Ads_iid);if(QQE!=5)
QQqC();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;QQkD(QQfB[Ads_sec]+'/dat/cjf/'+QQzD(IAS[2])+'.js');}QQk=Ads_cmb.length;for(QQl=0;QQl<QQk;QQl++)
{if(Ads_cmb[QQl]!='')
{QQx=Ads_cmb[QQl];Ads_cmb[QQl]='';QQl=QQk;Ads_pth='';Ads_iid='';eval(QQx);if(Ads_pth!='')
QQkD(QQfB[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
QQkD(QQfB[Ads_sec]+'/dat/cjf/'+QQzD(Ads_iid)+'.js');}}}function CAS()
{QQwC(0);}function CASF()
{var QQLa=new Date();Ads_T=[0,0,'',0,0,'','','','',QQLa,0,0,0,0,0];QQwC(1);}function QQwC(QQMa)
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var QQNa=new Date(Ads_T[9]);var QQOa=new Date();Ads_T[9]=QQNa-QQOa;	if (typeof(Ads_T[14])=='undefined')
		Ads_T[14]=0;	
var QQPa=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13]+'#'+Ads_T[14];	QQjC=Ads_T[14];QQfD('ASLTRG'+NUM_FARM+'='+QQPa+QQoD(60*((QQMa==0)? 24:1)));Ads_Data[NUM_FARM]=Ads_T;QQyD(1,'Load targeting-infos from server ('+((QQMa==0)? 'Origin':'Failover')+')',QQPa);if (QQsB==false)
{QQsB=true;SAS();}}function LAS(QQQa)
{Ads_iid=0;Ads_sec=(window.location.protocol.toLowerCase().indexOf('https')>-1)? 1:0;var QQb='pth='+QQQa+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
QQb+='&chn='+escape(Ads_channels);QQyA=false;document.write(QQtD(0,QQb));Ads_status[0]=[3,0,0,4];}function QQxC()
{QQwA=new Date();QQaB=-1;QQdB=0;QQzA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];QQyD(3,'Global Init');QQyD(1,'VAS Build Version:',Ads_Build);}function QQyC()
{if(typeof(Ads_sec)=='undefined') Ads_sec=IAS[1];QQyD(1,'Protocoll used',(Ads_sec==0)?'HTTP':'HTTPS');if(typeof(NUM_FARM)=='undefined')
NUM_FARM=1;if(typeof(Ads_farmid)!='undefined')
NUM_FARM=Ads_farmid;QQyD(1,'Setting configuration for farm',NUM_FARM);QQfB=[QQbA[NUM_FARM],QQcA[NUM_FARM]];QQgB=[QQhA[NUM_FARM],QQiA[NUM_FARM]];QQhB=[QQjA[NUM_FARM],QQkA[NUM_FARM]];QQiB=[QQdA[NUM_FARM],QQeA[NUM_FARM]];QQjB=[QQfA[NUM_FARM],QQgA[NUM_FARM]];}function QQzC()
{var QQPa=document.cookie+';';var QQRa=QQzA;var QQSa=QQPa.indexOf('ASLTRG'+NUM_FARM+'=');var QQTa,QQAa;if (typeof(Ads_Data[NUM_FARM])!='undefined')
{QQyD(1,'Load targeting-infos targeting array ['+NUM_FARM+']',Ads_Data[NUM_FARM]);Ads_T=Ads_Data[NUM_FARM];			QQkC=(QQPa.toLowerCase().indexOf('sestest')>-1);			QQfD('SESTEST=1'+QQoD(-1));			
return true;}if(QQSa!=-1)
{QQTa=QQPa.indexOf(';',QQSa);QQAa=QQPa.substring(QQSa+8,QQTa);Ads_T=QQAa.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);			if (typeof(Ads_T[14])=='undefined')
				Ads_T[14]=0;			QQjC=Ads_T[14];Ads_Data[NUM_FARM]=Ads_T;QQyD(1,'Load targeting-infos from cookie',QQAa);			QQkC=(QQPa.toLowerCase().indexOf('sestest')>-1);			QQfD('SESTEST=1'+QQoD(-1));return true;}else
{QQsB=false;QQyD(1,'#-#ASLDATA-load start','');QQkD(QQhB[Ads_sec]+ '?rdm='+QQvD());QQyD(1,'#-#ASLDATA-load ende','');return false;}}function QQaD(QQUa,QQVa,QQWa)
{return true;}function QQbD()
{var QQXa=(QQyA?1:0);QQXa+=((QQeB)?2:0);QQyD(1,'FLG',QQXa);return QQXa;}function QQcD(QQYa,QQZa)
{	
	
	QQyD(1,QQtA+'-QQcD1('+QQYa+','+QQZa+')',QQxB+':'+QQyB);if ((QQYa==QQxB)&&((QQZa==QQyB)||(QQZa!=0&&QQyB==0)))
return true;else
return false;}function QQdD(QQAb,QQBb)
{var QQCb;var QQDb;QQDb=false;if(!isNaN(QQAb))
{QQCb=parseInt(QQAb);QQDb=QQCb>=0&&(QQBb||QQCb>0);}return QQDb;}function QQeD(QQEb)
{var QQFb,QQGb;var QQHb,QQIb,QQJb,QQKb,QQLb,QQMb;var QQZ,QQNb,QQOb,QQPb,QQQb;var QQRb;var QQSb;QQFb=QQEb.split('-');QQSb=false;QQGb=[];QQRb=true;if(QQFb[0]!=null&&QQFb[1]!=null)
{QQHb=QQFb[0];QQIb=QQFb[1];QQRb=QQRb&&QQdD(QQIb,false);if(QQRb&&QQFb[2]!=null)
{QQJb=QQFb[2];QQRb=QQdD(QQJb,false);if(QQRb&&QQFb[3]!=null)
{QQKb=QQFb[3];QQRb=QQdD(QQKb,true);if(QQRb&&QQFb[4]!=null)
{QQLb=QQFb[4];if(QQRb&&QQFb.length>5)
{QQZ=5;while(QQRb&&QQZ<QQFb.length)
{if(QQFb[QQZ]==''&&QQFb[QQZ+1]!=null)
{QQMb=QQFb[QQZ+1];QQRb=QQdD(QQMb,true);QQGb[QQGb.length]='-'+QQMb;QQZ=QQZ+2;}else
{QQMb=QQFb[QQZ];QQRb=QQdD(QQMb,true);QQGb[QQGb.length]=QQMb;QQZ=QQZ+1;}}QQRb=QQRb&&(QQGb.length==0||QQGb.length==2||QQGb.length==4);}}}}if(QQRb)
{QQSb=[QQHb,QQIb,QQJb,QQKb,QQLb];for (var QQHc=0;QQHc<QQGb.length;QQHc++)
{QQSb[QQSb.length]=QQGb[QQHc];}}}return QQSb;}function QQfD(QQPa)
{	if (QQjC==1)
	{		QQgD();		return;	}	QQyD(1,'Write cookie',QQPa);document.cookie=QQPa;}function QQgD()
{	QQPa=document.cookie;	if (QQPa.indexOf('ASLTRG'+Ads_farmid+'=')!=-1)
		document.cookie='ASLTRG'+Ads_farmid+'=1'+QQnD(-2);	if (QQPa.indexOf('BSUID=')!=-1)
		document.cookie='BSUID=1'+QQnD(-2);	if (QQPa.indexOf('FRQSTR=')!=-1)
		document.cookie='FRQSTR=1'+QQnD(-2);	if (QQPa.indexOf('WIDYMD=')!=-1)
		document.cookie='WIDYMD=1'+QQnD(-2);	if (QQPa.indexOf('KIDYMD=')!=-1)
		document.cookie='KIDYMD=1'+QQnD(-2);	if (QQPa.indexOf('VISKAM=')!=-1)
		document.cookie='VISKAM=1'+QQnD(-2);	if (QQPa.indexOf('VISWEB=')!=-1)
		document.cookie='VISWEB=1'+QQnD(-2);	if (QQPa.indexOf('ASLTRG=')!=-1)
		document.cookie='ASLTRG=1'+QQnD(-2);	if (QQPa.indexOf('BNDLVL=')!=-1)
		document.cookie='BNDLVL=1'+QQnD(-2);	if (QQPa.indexOf('SESTEST=')!=-1)
		document.cookie='SESTEST=1'+QQnD(-2);	return;}function ASDC()
{if (typeof(Ads_debug)=='undefined')
Ads_debug=0;Ads_sec=QQVb=(window.location.protocol.toLowerCase().indexOf('https')>-1)?1:0;QQXb='http';QQyC();	
	QQyD(1,'Execute system default tracking',Ads_iid);	document.write('<div id="Ads_Count_'+Ads_iid+'" style="position:absolute;left:-1000;top:-1000;"><img src="'+QQgB[QQVb]+'/dat/bgf/trpix.gif?&rdm='+QQvD()+'&dlv=0,0,'+Ads_iid+',0,0&kid=0&iid='+Ads_iid+'&bid=0" width="1" height="1"></div>');if (Ads_Mapping[7]!=1)
{QQyD(1,'Invalid Tag type for Global redirector','Leaving redirector');return;}QQyD(1,'Executing Tag redirector for AdSpot',Ads_iid);var QQTb,QQUb,QQVb,QQWb,QQXb,QQYb,QQZb,QQAc,QQBc;QQUb='undefined';QQTb=QQiD();arrKeyword=QQhD();if (Ads_sec==1)
QQXb='https';QQYb='ord='+QQvD()+'?';QQAc='';QQBc='';if (Ads_Mapping[1]!=0)
QQAc='N'+Ads_Mapping[1]+'/';QQWb=QQXb+'://ad'+Ads_Mapping[0]+'.doubleclick.net/'+QQAc+'adj/'+Ads_Mapping[2]+'/'+Ads_Mapping[3]+';';QQlC=QQWb.length+Ads_Mapping[4].length+Ads_Mapping[6].length+QQYb.length;QQmC=2;if (Ads_Mapping[5]==1)
{QQBc='dcopt=ist;';QQmC++;}QQZb=Ads_Mapping[4].split(';');QQmC+=QQZb.length-1;QQyD(1,'Request Length',QQlC);QQWb+=Ads_Mapping[4]+QQBc+Ads_Mapping[6]+QQjD(QQTb)+QQjD(arrKeyword)+QQYb;QQyD(1,'Load following redirect',QQWb);QQyD(1,'Request Length:'+QQWb.length+' | Key-Value Pairs',QQmC);document.write('<scr'+'ipt language="JavaScript" src="'+QQWb+'"></scr'+'ipt>');}function QQhD()
{var QQCc,QQUb,QQDc,QQEc,QQFc,QQGc,QQHc;QQJc='';QQCc=[];QQUb='undefined';QQDc='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';if (typeof(Ads_wrd)!=QQUb)
{		if (Ads_wrd.toLowerCase()=='[keyword]')
			Ads_wrd='';QQyD(1,'Processing keyword data','');QQyD(1,'Ads_wrd',Ads_wrd);QQGc=Ads_wrd.length;QQFc='';for(QQHc=0;QQHc<QQGc;QQHc++)
{QQEc=Ads_wrd.charAt(QQHc);if(QQDc.indexOf(QQEc)!=-1)
QQEc='#';QQFc+=QQEc;}if (QQFc.charAt(0)!='#')
QQFc='#'+QQFc;arrWrd=QQFc.split('#');for (QQHc=0;QQHc<arrWrd.length;QQHc++)
{if (arrWrd[QQHc]!='')
QQCc[QQCc.length]='kw='+escape(arrWrd[QQHc]);}QQyD(1,'Keyword array',QQCc);}return QQCc;}function QQiD()
{var QQTb,QQUb,QQDc,QQEc,QQIc,QQJc,QQGc,QQHc,QQKc,QQLc,QQMc,QQNc,QQOc;QQJc='';QQTb=[];QQUb='undefined';QQDc='!"%&\'()*+,-./:;<>?@[\\]^{|}~§ ';QQOc='#abr#dcopt#dcove#dcovd#ov#dom#kw#ord#provider#sz#ptile#tile#category#tn#tw#twp#th#thp#to#szs#tsw#tsc#tcp#tcs#ta#tva#tbw#tbc#tc#dcaff#dcafs#tnm#tek#te#pos#';if (typeof(Ads_PrfMap)==QQUb||typeof(Ads_prf)==QQUb)
{QQyD(1,'No Profile Data Available','');return QQTb;}else
{		if (Ads_prf.toLowerCase()=='[profile]')
			Ads_prf='';QQyD(1,'Processing profile data','');QQyD(1,'Ads_prf',Ads_prf);QQyD(1,'Ads_PrfMap',Ads_PrfMap);QQGc=Ads_prf.length;QQIc='';for(QQHc=0;QQHc<QQGc;QQHc++)
{QQEc=Ads_prf.charAt(QQHc);if(QQDc.indexOf(QQEc)!=-1)
QQEc='#';QQIc+=QQEc;}if (QQIc.charAt(0)!='#')
QQIc='#'+QQIc;arrPrf=QQIc.split('#');QQyD(1,'array profile',arrPrf);QQMc=QQIc;for (QQHc=0;QQHc<arrPrf.length;QQHc++)
{if (arrPrf[QQHc]!='');{QQNc=arrPrf[QQHc].split('=');if (QQNc[0].length<6&&QQNc[0]!=''&&QQOc.indexOf('#'+QQNc[0]+'#')<0)
{QQyD(1,'Within Size Limit. Adding',QQNc[0]);QQTb[QQTb.length]=QQNc[0]+'='+escape(QQNc[1]);}else
{for (QQKc=0;QQKc<Ads_PrfMap.length;QQKc++)
{if (Ads_PrfMap[QQKc]==QQNc[0])
{QQyD(1,'Found '+Ads_PrfMap[QQKc]+'. Adding',Ads_PrfMap[QQKc+1]);QQTb[QQTb.length]=Ads_PrfMap[QQKc+1]+'='+escape(QQNc[1]);}QQKc++;}}}}QQyD(1,'Profile Array',QQTb);return QQTb;}}function QQjD(QQPc)
{var QQQc='';for (var QQHc=0;QQHc<QQPc.length;QQHc++)
{if ((QQlC+QQPc[QQHc].length +1)<2048&&QQmC<255)
{QQQc+=QQPc[QQHc]+';';QQlC+=QQPc[QQHc].length+1;QQmC++;}}return QQQc;}QQxC();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
function QQoI(QQCi,QQOk)
{return (QQCi==0)?'':' '+QQOk+'="'+QQCi+'"';}function QQpI(QQt,QQBa,QQz,QQJ,QQa,QQAa,QQf,QQg,QQF,QQW,QQU,QQd,QQM,QQN)
{QQJ=QQrC(QQJ);if(QQBa&&QQW&&!QQTk)
{QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQM+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQN+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQyD(1,'Sidebar',QQp);QQtSide=window.open(QQp,QQU);}else
{if(QQBa)
QQtI(QQt,QQF);/*
QQt.document.write('<a href="'+QQsC(QQa,QQz[0]) +'" target="'+QQAa+'" '+QQbB+'onmouseout="self.status=\'\';return true;">');QQt.document.write('<img src="'+QQJ+'"'+QQoI(QQf,'width')+QQoI(QQg,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+QQF+'"></a>');*/
QQt.document.write('<a href="'+Ads_ClickUrl +'" target="'+QQAa+'" '+QQbB+'onmouseout="self.status=\'\';return true;">');QQt.document.write('<img src="'+QQJ+'"'+QQoI(QQf,'width')+QQoI(QQg,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+QQF+'"></a>');QQuD(QQt,QQz[1]);if(QQBa)
QQuI(QQt);}if (QQcD(Ads_iid,QQtA))
{			QQyD(1,'Reset Internal Redirect Data','');QQtB='';QQvB=0;}}function QQqI(QQt,QQBa,QQz,QQD,QQa,QQAa,QQf,QQg,QQF,QQH,QQI,QQGa,QQQ,QQV)
{if(QQBa)
QQtI(QQt,QQF);/*
QQa=QQsC(QQa,QQAmString);QQI=QQsC(QQI,QQAmString);*/
QQa=Ads_ClickUrl;QQI=Ads_ClickAltUrl;QQD=QQiB[Ads_sec]+'/dat/bgf/'+QQD;QQH=QQiB[Ads_sec]+'/dat/bgf/'+QQH;QQnC=QQa;var QQRk=QQD;if(typeof(QQV)=='undefined') QQV='';if(QQV=='')
QQRk+='?clickTag='+escape(QQa)+'&url='+escape(QQa);else if(QQV!='0')
QQRk+='?'+QQV+'='+escape(QQa);var QQNd;if(QQQ<=QQbE(1))
{			
QQt.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+QQoI(QQf,'width')+QQoI(QQg,'height')+'">');QQt.document.write('<PARAM NAME=movie VALUE="'+QQRk+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');QQt.document.write('<EMBED src="'+QQRk+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+QQoI(QQf,'width')+QQoI(QQg,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{QQt.document.write('<a href="'+QQI+'" target="'+QQAa+'" '+QQbB+' onmouseout="self.status=\'\';return true;"><img src="'+QQH+'"'+QQoI(QQf,'width')+QQoI(QQg,'height')+' border="0" alt="'+QQF+'"></a>');}QQuD(QQt,QQz[1]);if(QQBa)
QQuI(QQt);if (QQcD(Ads_iid,QQtA))
{			QQyD(1,'Reset Internal Redirect Data','');QQtB='';QQvB=0;}}function QQrI(QQt,QQBa,QQz,QQc,QQd,QQy,QQHa,QQf,QQg,QQT,QQU,QQw,QQQa,QQSk,QQW,QQTk,QQE)
{var QQD=QQfB[Ads_sec]+QQQa+QQzD((QQSk>0)?QQSk:((QQT==0)?QQd:QQT));var QQUk,QQZg;var QQVk=[];QQVk=QQpD(QQc,QQd,QQy);iid=Ads_iid;bid=QQd;rdm=QQVk[2];if(QQBa||((QQHa||QQw)&&(QQqB||QQrB)))
{var QQWk='*';for(QQZg=1;QQZg<Ads_MultiUrl.length;QQZg++)
{QQa=Ads_MultiUrl[QQZg];QQWk+=QQa.substring(Ads_CountUrl.length,QQa.length)+'*';}QQUk=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQbD()+'&')+'#'+Ads_LinkUrl+'#'+QQWk+'#'+QQrD() +'#'+Ads_cnturl +'#'+QQE;}if(QQBa&&QQW&&!QQTk)
{window.open(QQD+'.html?'+escape(QQUk),QQU);}else if(QQBa)
{QQt.location.href=QQD+'.html?'+escape(QQUk);}else if((QQHa||QQw)&&(QQqB||QQrB))
{document.write('<iframe src="'+QQD+'.html?'+escape(QQUk)+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{rdm=QQVk[0];if(QQSk>0)
{Ads_xl=QQf;Ads_yl=QQg;QQuD(QQt,QQz[1]);if ((Ads_opt&4096)>0)
{QQyD(1,'Serve AFX Out Of Frame','');var QQWk='*';for(QQZg=1;QQZg<Ads_MultiUrl.length;QQZg++)
{QQa=Ads_MultiUrl[QQZg];QQyD(1,'Ads_MultiUrl['+QQZg+']',QQa.substring(Ads_CountUrl.length,QQa.length));QQaShort=QQa.substring(Ads_CountUrl.length,QQa.length);QQyD(1,'Index of',QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx="));if (QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx=")>=0)
{QQWk+='PX'+QQaShort.substring(QQaShort.indexOf('&')+5,QQaShort.length)+'*';}else
{QQWk+=QQaShort+'*';}}QQyD(1,'QQWk',QQWk);QQUk=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQbD()+'&')+'#'+Ads_LinkUrl+'#'+QQWk+'#'+QQrD()+'#'+NUM_FARM+'#'+QQfB[Ads_sec]+'#'+QQSk;var QQXk=document.referrer;var QQYk='';var QQZk='';var QQAl=QQXk.indexOf('://');if (QQAl>-1)
{QQYk=QQXk.substring(0,(QQAl+3));QQZk=QQXk.substring((QQAl+3),QQXk.length);var QQAl=QQZk.indexOf('/');if (QQAl>-1)
QQZk=QQZk.substring(0,QQAl);}QQyD(1,'Loading ',QQYk+QQZk+'/afx_frame.html?'+ escape(QQUk));document.write('<iframe src="'+QQYk+QQZk+'/afx_frame.html?'+escape(QQUk)+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{if ((typeof(Ads_FXPL)=='undefined')||(Ads_FXPL==false))
{QQkD(QQfB[Ads_sec]+'/dat/dlv/afxplay.js');Ads_FXPL=true;}QQkD(QQD+'.js');}}else
QQkD(QQD+'.js');}if (QQcD(Ads_iid,QQtA))
{			QQyD(1,'Reset Internal Redirect Data','');QQtB='';QQvB=0;}}function QQsI(QQt,QQBa,QQz,QQK,QQL,QQHa,QQf,QQg,QQw)
{QQL=QQrC(unescape(QQL));QQK=QQrC(unescape(QQK));if(QQBa)
QQt.location.href=QQK;else
{if(((QQHa||QQw)&&QQqB)||(QQL==''))
document.write('<iframe src="'+QQK+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
QQkD(QQL);}QQuD(window,QQz[1]);if (QQcD(Ads_iid,QQtA))
{			QQyD(1,'Reset Internal Redirect Data','');QQtB='';QQvB=0;}}function QQtI(QQt,QQF)
{QQt.document.open();QQt.document.write('<html><head><title>'+QQF+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function QQuI(QQt)
{QQt.document.write('</center></td></tr></table></body></html>');QQt.document.close();}function QQvI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQBl='Ads_Popup'+Ads_iid;var QQCl,QQDl;var QQEl=0;var QQFl=0;if (!QQW&&QQU!='')
QQBl=QQU;QQu=QQwI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQTk);if((Ads_opt&32)>0)
QQBl+=''+Math.round(Math.random()*100000);QQt=open('',QQBl,QQu);if(QQDa&&(!QQnB))
QQt.moveTo(0,0);if(QQEa)
QQlI(QQt,QQf,QQg);return QQt;}function QQwI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQTk)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQBl='Ads_Popup'+Ads_iid;var QQCl,QQDl;var QQEl=0;var QQFl=0;if (!QQW&&QQU!='')
QQBl=QQU;if(QQDa)
{if (QQoB)
{QQEl=10;QQFl=30;}else if (QQpB)
{QQEl=20;QQFl=35;}QQu+=',scrollbars=no,resizable=no,width='+(screen.availWidth-QQEl)+',height='+(screen.availHeight-QQFl)+',screenX=0,screenY=0';if(QQnB)
QQu='fullscreen=yes';}else
{if(QQEa)
QQu+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
QQu+=',resizable=no,width='+QQf+',height='+QQg;if(QQFa)
QQu+=',scrollbars=yes';else
QQu+=',scrollbars=no';if((Ads_opt&64)>0)
QQu='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+QQf+',height='+QQg;if(QQZ==16)
{QQM=(screen.width-QQf-25)*QQM/100;QQN=(screen.height-QQg-50)*QQN/100;}else if(QQZ==24)
{QQM=(screen.width-QQf-25)*Math.random();QQN=(screen.height-QQg-50)*Math.random();}if (!QQqB)
QQu+=",screenX="+QQM+",screenY="+QQN;else
QQu+=",left="+QQM+",top="+QQN;}return QQu;}function QQxI(QQtA,QQd,QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,QQU,QQTk,QQKa)
{var QQGl='';QQGl='<scr'+'ipt language="JavaScript">'+'function Ads_PopUp() {';if (Ads_cmd!='win'&&QQTk&&(QQd>0))
{QQyD(1,'POP ON EXIT','');var QQBl='Ads_Popup'+Ads_iid;if (!QQW&&QQU!='')
QQBl=QQU;if((Ads_opt&32)>0)
QQBl+=''+Math.round(Math.random()*100000);QQu=QQwI(QQf,QQg,QQM,QQN,QQZ,QQDa,QQCa,QQR,QQEa,QQFa,QQW,'',true);QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQM+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQN+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQkB[QQkB.length]='QQt=open(\''+QQp+'\',\''+QQBl+'\',\''+QQu+'\');';}for (var QQHc=0 ;QQHc<QQkB.length ;QQHc++)
{QQGl+=QQkB[QQHc];}QQGl+=QQKa;QQGl+='}'+'</scr'+'ipt>';document.writeln(QQGl);}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
var QQfF=[];var QQgF=[];var QQhF;function QQiF(QQPh,QQQh,QQRh,QQOf)
{if(typeof(QQPh)=='undefined')
return [];var QQl,QQk;var QQSh=[];var QQTh=QQPh.split('x');var QQUh=QQTh[0];var QQVh=QQQh-QQUh;var QQk=QQTh.length;QQgF[QQOf]=[];for(QQl=1;QQl<QQk;QQl++)
{QQAj=QQTh[QQl].split(':');if(QQRh&&(QQAj[2]==-1))
QQSh[QQAj[0]]=[QQAj[1],-1];QQAj[2]-=QQVh;if(QQAj[2]>0)
QQSh[QQAj[0]]=[QQAj[1],QQAj[2]];if (typeof(QQgF[QQOf])=='undefined')
QQgF[QQOf]=[];QQgF[QQOf][QQgF[QQOf].length]=QQAj[0];}return QQSh;}function QQjF(QQSh,QQQh,QQOf)
{var QQPd;var QQPh=QQQh;var QQl;if (typeof(QQgF[QQOf])!='undefined')
{for (var QQHc=0;QQHc<QQgF[QQOf].length;QQHc++)
{QQl=QQgF[QQOf][QQHc];if (typeof(QQSh[QQl])!='undefined')
{QQPh+='x'+QQl+':'+QQSh[QQl][0]+':'+QQSh[QQl][1];}}}return QQPh;}function QQkF(QQWh,QQXh)
{while(QQWh.length>800)
QQWh=QQWh.substr(0,QQWh.lastIndexOf('#',QQWh.length-2)+1);QQfF[QQXh]=QQWh;}function QQlF(QQXh,QQCb)
{var QQYh='111';var QQZh='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var QQk=0;var QQAb='#'+QQCb+':';var QQWh=QQfF[QQXh];var QQAi='';var QQZ=QQWh.indexOf(QQAb);var QQBi=new Date();var QQCi,QQDi,QQEi,QQFi,QQEf;var QQGi,QQHi,QQIi,QQJi;if(QQWh=='')
QQWh='#';if(QQZ>-1)
{QQDi=QQWh.substr(QQZ+QQAb.length,3+QQXh);if(QQZ>0)
QQAi=QQWh.substr(0,QQZ);QQCi=QQWh.length-QQZ-QQAb.length-3-QQXh;if(QQCi>0)
QQAi+=QQWh.substr(QQZ+QQAb.length+3+QQXh,QQCi);QQWh=QQAi;QQEi=new Date(QQZh.indexOf(QQDi.charAt(0))+2000,QQZh.indexOf(QQDi.charAt(1))-1,QQZh.indexOf(QQDi.charAt(2)));QQBi.setHours(0);QQBi.setMinutes(0);QQBi.setSeconds(0);QQFi=(QQBi.getTime()-QQEi.getTime())/1000/60/60/24;intAltWTag=(QQEi.getDay()==0?7:QQEi.getDay());intNeuWTag=(QQBi.getDay()==0?7:QQBi.getDay());intAltMTag=QQEi.getDate();intNeuMTag=QQBi.getDate();QQYh=((QQFi>0.1)?'1':'0')+(((QQFi>6)||(intAltWTag>intNeuWTag))?'1':'0')+((((QQFi>29)||(intAltMTag>intNeuMTag))&&(QQXh!=1&&QQXh!=14))?'1':'0');if(QQXh==1||QQXh==14)
QQk=QQZh.indexOf(QQDi.charAt(3));}QQDi='#'+QQCb+':';QQEf=QQBi.getYear();if(QQEf<1900)
QQEf+=1900;QQDi+=QQZh.charAt(QQEf-2000);QQDi+=QQZh.charAt(QQBi.getMonth()+1);QQDi+=QQZh.charAt(QQBi.getDate());if(QQXh==1||QQXh==14)
{QQk++;if(QQk>21)
QQk=21;QQDi+=QQZh.charAt(QQk);QQYh+=QQZh.charAt(QQk);}QQWh=QQDi+QQWh;QQkF(QQWh,QQXh);return QQYh;}function QQmF(QQAb,QQXh,QQKi)
{var QQSa,QQTa,QQCi,QQLi,QQMi;var QQWh=QQfF[QQXh];var QQAi='';var QQNi='';var QQOi=-1;if(QQWh=='')
QQWh='#';QQAb='#'+QQAb+'-';QQSa=QQWh.indexOf(QQAb);if(QQSa!=-1)
QQTa=QQWh.indexOf('#',QQSa+1);if((QQSa!=-1)&&(QQTa!=1))
{QQLi=QQWh.substring(QQSa+QQAb.length,QQTa);if(QQSa>0)
QQAi=QQWh.substr(0,QQSa);QQCi=QQWh.length-QQTa;if(QQCi>0)
QQAi+=QQWh.substr(QQTa,QQCi);QQWh=QQAi;if(QQXh==6)
{QQMi=QQLi.split('-');QQNi=QQMi[0];QQLi=QQMi[1];}QQOi=QQKi-parseInt(QQLi,10);if(QQOi>1200)
QQOi=-1;}QQfF[QQXh]=QQWh;return [QQOi,QQNi];}function QQnF(QQc)
{var QQPi=new Date();var QQOi=QQPi.getHours()*60*60+QQPi.getMinutes()*60+QQPi.getSeconds();var QQQi,QQRi;QQQi=QQmF(Ads_wid,6,QQOi);QQRi=QQmF(QQc,5,QQOi);var QQSi=(QQQi[0]==-1);var QQTi=(QQRi[0]==-1);var QQUi=(QQSi?'1':'0')+(QQTi?'1':'0');if(!QQSi)
QQUi+=QQwD(QQQi[0],4)+QQQi[1];QQkF('#'+Ads_wid+'-'+Ads_iid+'-'+QQOi+QQfF[6],6);QQkF('#'+QQc+'-'+QQOi+QQfF[5],5);return QQUi;}function QQoF()
{var QQUc=QQmD();var QQl,QQVi,QQPd,QQWi,QQXi,QQYi,QQZi,QQAj,QQXh;var QQBj,QQCj;var QQPa=document.cookie;var QQRh=QQkC;		QQyD(1,'Session Cookie',QQRh);var QQDj=QQPa.split(';');var QQk=QQDj.length;var QQKd=new Date();QQhF=Math.round(QQKd.getTime()/1000/60);QQfF=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];QQfF=QQpF('',QQDj,QQk,QQRh);if(Ads_uid!='')
{QQDj=Ads_userdata.split(';');QQk=QQDj.length;QQfF[2]=[];for(QQl=1;QQl<(QQk-1);QQl++)
{QQYi=QQDj[QQl].split(',');QQfF[2][QQYi[0]]=[QQYi[1],1];}}if(QQfF[3]=='1')
QQzA=true;	
	if (IAS[18]==0)
	{		QQyD(1,'VISKAM',QQfF[5]);		QQyD(1,'VISWEB',QQfF[6]);	}}function QQpF(QQUc,QQDj,QQk,QQRh)
{var QQl;var QQfF;var QQPd;QQfF=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];for(QQl=0;QQl<QQk;QQl++)
{QQXh=-1;QQYi=QQDj[QQl].split('=');QQPd=QQYi[0];QQXi=QQYi[1];if(QQPd.charAt(0)==' ')
QQPd=QQPd.substr(1,QQPd.length-1);if(QQPd.substr(0,QQUc.length)==QQUc)
QQWi=QQPd.substring(QQUc.length,QQPd.length);else
QQWi='';if(QQWi=='KIDYMD')
QQfF[1]=QQXi;else if(QQWi=='WIDYMD')
QQfF[0]=QQXi;else if(QQPd=='SESTEST')
QQfF[3]=QQXi;else if(QQPd=='BNDLVL')
QQfF[10]=QQXi;		 else if(IAS[18]==0&&QQWi=='VISKAM')
QQfF[5]=QQXi;else if(IAS[18]==0&&QQWi=='VISWEB')
QQfF[6]=QQXi;			else if(QQWi=='FRQSTR')
{if (QQXi.indexOf("|")!=-1)
QQYi=QQXi.split('|');else
QQYi=QQXi.split(',');QQfF[2]=QQiF(QQYi[0],QQhF,QQRh,2);QQfF[7]=QQiF(QQYi[1],QQhF,QQRh,7);QQfF[8]=QQiF(QQYi[2],QQhF,QQRh,8);QQfF[9]=QQiF(QQYi[3],QQhF,QQRh,9);QQfF[12]=QQiF(QQYi[4],QQhF,QQRh,12);}if(QQWi=='KIDCYMD')
QQfF[14]=QQXi;else if(QQWi=='WIDCYMD')
QQfF[13]=QQXi;}return QQfF;}function QQqF(QQc,QQKe)
{var QQEj,QQFj,QQZe,QQGj;var QQHj='';var QQUc=QQmD();var QQIj=KAS[QQKe][4][5];if(KAS[QQKe][4][4]>0)
QQHj=QQnD(QQIj);else if((KAS[QQKe][5]&1)>0)
{QQHj=QQnD(20);QQIj=20;}if(QQHj!='')
{QQZe=parseInt(QQsF(QQc,2)+1,10);if(Ads_uid!='')
{QQEj=Ads_userdata.split(';'+QQc+',');if(QQEj.length==2)
{QQFj=Ads_userdata.split(','+QQc+';');Ads_userdata=QQEj[0]+';'+QQFj[1];}Ads_userdata+=QQc+','+QQZe+','+QQIj+','+QQc+';';document.write('<img src="http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random()+'" width="1" height="1">');}else
QQtF(QQc,2,QQZe,QQIj);}}function QQrF(QQc,QQKe,QQd,QQs,QQJj)
{var QQUc=QQmD();var QQy=[];var QQKj,QQPa,QQLj;QQqF(QQc,QQKe);if(QQd>0)
{if(BAS[QQs][2][4]>0)
QQtF(QQd,9,QQsF(QQd,9)+1,BAS[QQs][2][5]);}if(((KAS[QQKe][4][22]&1)>0)&&(IAS[4]>0))
QQtF(Ads_wid,7,QQsF(Ads_wid,7)+1,IAS[5]);if(((KAS[QQKe][4][22]&2)>0)&&(IAS[6]>0))
QQtF(Ads_nid,8,QQsF(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(QQbC[Ads_wid])!='undefined')&&(typeof(KAS[QQKe][13])!='undefined'))
{if(((KAS[QQKe][4][22]&4)>0)&&(KAS[QQKe][13]>0)&&(QQbC[Ads_wid].length>0)&&(typeof(QQbC[Ads_wid][KAS[QQKe][13]])!='undefined'))
{arrFamily=QQbC[Ads_wid][KAS[QQKe][13]];QQtF(arrFamily[0],12,QQsF(arrFamily[0],12)+1,arrFamily[2]);}}QQPa=QQjF(QQfF[2],QQhF,2)+'|' +QQjF(QQfF[7],QQhF,7)+'|' +QQjF(QQfF[8],QQhF,8)+'|' +QQjF(QQfF[9],QQhF,9)+'|' +QQjF(QQfF[12],QQhF,12);QQKj=QQlF(1,QQc);QQLj=QQKj.substr(0,3)+QQlF(0,Ads_wid)+QQKj.substr(3,1);QQy[1]='&bls3='+QQLj;QQuB=QQLj;		if (IAS[18]==0)
			QQy[1]+='&bls4='+QQnF(QQc);QQAmAuswertung=QQlF(14,QQc);QQy[0]='&ucl='+QQAmAuswertung.substr(0,3)+QQlF(13,Ads_wid)+QQAmAuswertung.substr(3,1);if(QQzA)
QQy[1]+='&uid=1';QQyD(1,'SETTING TOP-LEVEL DOMAIN',QQPa);QQfD('FRQSTR='+QQPa+QQoD(60*24*365));QQfD('WIDYMD='+QQfF[0]+QQoD(60*24*30));QQfD('KIDYMD='+QQfF[1]+QQoD(60*24*30));		if (IAS[18]==0)
		{			QQfD('VISKAM='+QQfF[5]+QQoD(20));			QQfD('VISWEB='+QQfF[6]+QQoD(20));		}QQyD(1,'Cookie Auswertung [Click/Impression]',QQy[0]+'/'+QQy[1]);return QQy;}function QQsF(QQCb,QQOf)
{if(typeof(QQfF[QQOf][''+QQCb+''])!='undefined')
return parseInt(QQfF[QQOf][''+QQCb+''],10);else
return 0;}function QQtF(QQCb,QQOf,QQZe,QQIj)
{if(typeof(QQfF[QQOf][''+QQCb+''])!='undefined')
QQfF[QQOf][''+QQCb+''][0]=QQZe;else
{if (typeof(QQgF[QQOf])=='undefined')
QQgF[QQOf]=[];QQgF[QQOf][QQgF[QQOf].length]=QQCb;QQfF[QQOf][''+QQCb+'']=[QQZe,QQIj];}}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
function QQgE(QQWd,QQXd)
{var QQl=0;var QQk=QQWd.length;if(QQk==0)
return -1;while((QQl<QQk-1)&&(QQXd>QQWd[QQl][1]))
{QQXd-=QQWd[QQl][1];QQl++;}return QQWd[QQl][0];}function QQhE(QQYd,QQZd,QQAe)
{var QQl,QQBe,QQCe,QQDe;if(QQYd>QQAe)
{QQBe=QQAe/QQYd;for(QQl=QQZd;QQl<QQlB.length;QQl++)
QQlB[QQl][1]*=QQBe;QQYd=QQAe;}QQAe-=QQYd;return QQAe;}function QQiE()
{var QQDb,QQEe,QQFe,QQGe,QQHe;var QQIe=-2;var QQJe=KAS.length;var QQAe=100;var QQKe,QQc,QQDe,QQLe,QQMe,QQNe,QQOe,QQPe,QQQe;var QQYd=0;var QQZd;QQlB=[];for (QQKe=0;QQKe<QQJe;QQKe++)
{QQHe=((KAS[QQKe][5]&2)>0);if(KAS[QQKe][2]!=QQIe)
{if(QQIe!=-2)
QQAe=QQhE(QQYd,QQZd,QQAe);QQIe=KAS[QQKe][2];QQYd=0;QQZd=QQlB.length;}QQLe=KAS[QQKe][8];QQMe=KAS[QQKe][10];QQNe=IAS[10];if((QQNe-QQMe)>0)
QQLe=QQLe*QQNe/(QQNe-QQMe);QQDe=KAS[QQKe][1];if(QQLe<=0)
QQLe=QQDe;QQOe=(QQDe/QQLe-1)*2+1;var QQRe=QQOe;var QQSe=false;if (QQOe>10||QQOe<0.1)
QQSe=true;if(QQOe>10)
QQOe=10;else if (QQOe<0.1)
QQOe=0.1;if (QQSe)
QQyD(1,'Factor (before:after)',QQRe+':'+QQOe);QQPe=KAS[QQKe][3];QQDe=QQDe*QQOe*100/((QQPe==0)?100:QQPe);if(isNaN(QQDe))
QQDe=0;QQGe=KAS[QQKe][4];QQDb=QQaF(QQGe,0,KAS[QQKe][0],((KAS[QQKe][5]&4)>0),QQKe);QQFe=false;if(QQGe.length>0)
{QQFe=((QQGe[0]==0)&&!((QQGe[2]==0)&&(QQGe[3]==1439)));QQEe=(!QQFe||QQyE(QQGe[2],QQGe[3]));if(QQFe)
QQDe=QQDe*100/KAS[QQKe][9];if(QQDb&&!QQEe&&!QQHe)
{QQqA+='9'+KAS[QQKe][0]+'-';}QQDb=(QQDb&&QQEe);}if((KAS[QQKe][5]&8)>0)
QQDe=KAS[QQKe][1];if(QQHe&&QQDb)
{QQc=KAS[QQKe][0];QQrA+=QQc+'-';QQqF(QQc,QQKe);}else if(QQDb)
{QQlB[QQlB.length]=[QQKe,QQDe,QQFe,QQDe];QQYd+=QQDe;}else
{}}QQAe=QQhE(QQYd,QQZd,QQAe);}function QQjE()
{QQiE();var QQTe,QQKe,QQl,QQDe;var QQJe=QQlB.length;var QQUe=0;for (QQKe=0;QQKe<QQJe;QQKe++)
{QQl=QQlB[QQKe][0];QQDe=QQlB[QQKe][1];QQTe=Math.round(QQDe/QQlB[QQKe][3]*10)-1;if(QQTe>9)
QQTe=9;if((QQTe>=0)&&(KAS[QQl][0]>0))
QQqA+=QQTe+''+KAS[QQl][0]+'-';QQUe+=QQDe;}return QQgE(QQlB,QQUe*Math.random());}function QQkE(QQKe,QQc)
{var QQVe=[];var QQWe=BAS.length;var QQXe=((KAS[QQKe][5]&1)>0);var QQUe=0;var QQs,QQDe,QQYe,QQZe,QQAf,QQBf;var QQCf=true;for (QQs=0;QQs<QQWe;QQs++)
{strInhalt=BAS[QQs][21];QQBf=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[QQs][13]>1)||(BAS[QQs][14]>1)))
{QQCf=((Ads_xl==BAS[QQs][13])&&(Ads_yl==BAS[QQs][14]));}if(QQCf&&QQBf&&QQaF(BAS[QQs][2],1,BAS[QQs][0],true,QQs))
{QQDe=BAS[QQs][1];QQVe[QQVe.length]=[QQs,QQDe];QQUe+=QQDe;}else
{}}QQWe=QQVe.length;if(QQXe)
{QQZe=QQsF(QQc,2);if(QQWe>0)
QQs=QQVe[QQZe%QQWe][0];else
QQs=-1;}else
QQs=QQgE(QQVe,QQUe*Math.random());return QQs;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000078-2)
var QQlE=false;var QQmE;var QQnE;var QQoE =(typeof(QQoE)=='undefined')? 0:QQoE;function QQpE(QQDf)
{return QQwD(QQDf.getHours(),2)+':'+QQwD(QQDf.getMinutes(),2)+':'+QQwD(QQDf.getSeconds(),2);}function QQqE(QQDf)
{var QQEf=QQDf.getYear();if(QQEf<1900)
QQEf+=1900;return QQwD(QQEf,4)+'-'+QQwD(QQDf.getMonth()+1,2)+'-'+QQwD(QQDf.getDate(),2);}function QQrE()
{if(QQlE)
return;var QQFf,QQGf,QQHf,QQl,QQIf;var QQJf=new Date();var QQKf=new Date();QQKf.setTime(QQJf-0+parseInt(Ads_T[9],10));QQFf=QQfF[1].split('#');QQGf=QQFf.length-1;QQHf=',';for(QQl=1;QQl<QQGf;QQl++)
{QQIf=QQFf[QQl].split(':');QQHf+=QQIf[0]+',';}QQlE=true;QQmE=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+QQbE(0) +';user-day='+(QQJf.getDay()==0?7:QQJf.getDay()) +';user-time='+QQpE(QQJf) +';user-date='+QQqE(QQJf) +';server-day='+(QQKf.getDay()==0?7:QQKf.getDay()) +';server-time='+QQpE(QQKf) +';server-date='+QQqE(QQKf) +';campaigns='+QQHf +';';if(navigator.appVersion.substring(0,1)>'3')
{var QQLf=0;var QQMf=0;if (typeof(window.innerWidth)=='undefined'&&document.body!=null)
{QQLf=document.body.clientWidth;QQMf=document.body.clientHeight;}else
{QQLf=window.innerWidth;QQMf=window.innerHeight;}QQmE+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+QQLf +';window-height='+QQMf +';color-depth='+screen.colorDepth +';';}QQyD(1,'Environment values',QQmE);}function QQsE(QQNf,QQk,QQCb,QQOf,QQPf,QQQf,QQRf)
{var QQSf;if((QQk>0)&&(QQNf>0))
{QQSf=((QQsF(QQCb,QQOf)<QQk)&&(QQzA||QQRf));if((QQSf?1:0)==QQPf)
return QQPf;QQnE[QQQf]=QQSf;}return 2;}function QQtE(QQTf,QQUf,QQVf,QQPf,QQQf)
{var QQSf;if(QQTf.length>1)
{QQSf=(QQTf.indexOf('#'+QQUf+'#')!=-1);QQSf=QQVf>0?!QQSf:QQSf;QQnE[QQQf]=QQSf;if((QQSf?1:0)==QQPf)
return QQPf;}return 2;}function QQuE(QQNf,QQWf,QQCb,QQOf,QQPf,QQQf,QQRf)
{var QQSf=true;if (typeof(QQWf)=='undefined')
QQWf=[];if (typeof(QQbC[Ads_wid])=='undefined')
QQbC[Ads_wid]=[];if(QQNf>0&&QQCb>0)
{if ((QQWf.length>0)&&(QQbC[Ads_wid].length==0))
{for (QQHc=0 ;QQHc<QQWf.length ;QQHc++)
{QQbC[Ads_wid][QQWf[QQHc][0]]=[QQWf[QQHc][1],QQWf[QQHc][2],QQWf[QQHc][3]];if (QQWf[QQHc][0]==QQCb)
{QQvIndex=QQHc;}}if (typeof(QQvIndex)=='undefined')
return 2;intReturn=QQsE(QQNf,QQWf[QQvIndex][2],QQWf[QQvIndex][1],QQOf,QQPf,QQQf,QQRf);return intReturn;}else if (QQbC[Ads_wid].length>0)
{if (typeof(QQbC[Ads_wid][QQCb])=='undefined')
return 2;intReturn=QQsE(QQNf,QQbC[Ads_wid][QQCb][1],QQbC[Ads_wid][QQCb][0],QQOf,QQPf,QQQf,QQRf);return intReturn;}}return 2;}function QQvE(QQTf,QQVf,QQPf,QQXf,QQQf)
{if(QQTf=='')
return 2;var QQl,QQBd,QQYf,QQZf,QQEc,QQAg,QQBg,QQCg,QQDg;var QQDc='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var QQSf=false;QQTf=QQTf.substr(1,QQTf.length-2);var QQGe=QQTf.split('#');var QQk=QQGe.length;if(QQk>0)
{if(QQXf)
{QQBd='';QQAg=Ads_wrd.length;for(QQl=0;QQl<QQAg;QQl++)
{QQEc=Ads_wrd.charAt(QQl);if(QQDc.indexOf(QQEc)!=-1)
QQEc='#';QQBd+=QQEc;}QQBd='#'+QQBd.toLowerCase()+'#';QQYf=QQBd;}else
{QQBd='#'+Ads_T[5]+'#';arrIP=Ads_T[6].split('.');QQYf='';for (var QQHc=0;QQHc<arrIP.length;QQHc++)
{if (QQHc!=0)
QQYf+='.';QQYf+=QQwD(parseInt(arrIP[QQHc]),3);}QQYf='#'+QQYf+'#';}for(QQl=0;(QQl<QQk)&&(QQSf==false);QQl++)
{QQCg=QQGe[QQl].toLowerCase();QQBg=false;if(QQCg.substring(0,1)=='$')
{QQCg=QQCg.substring(1,QQCg.length);QQBg=true;}QQZf=false;QQDg=QQBd;if(QQCg.substring(0,1)=='!')
{QQCg=QQCg.substring(1,QQCg.length);QQDg=QQYf;QQZf=true;}if(QQXf)
QQCg='#'+QQCg;if(!QQZf)
QQCg+='#';QQSf=(QQDg.indexOf(QQCg)!=-1);if (QQZf)
QQyD(1,'IP Targeting',QQSf);if(QQBg)
{QQSf=!QQSf;QQl=QQk;}}QQSf=QQVf>0?!QQSf:QQSf;if((QQSf?1:0)==QQPf)
return QQPf;QQnE[QQQf]=QQSf;}return 2;}function QQwE(QQEg,QQFg)
{var QQGg=[];var QQHg=0;var QQl,QQIg;var QQk=QQEg.length;for(QQl=0;QQl<QQk;QQl++)
{QQIg=QQEg[QQl];if(QQIg>=0)
{QQGg[QQHg]=QQFg[QQIg];QQHg++;}else if(QQIg==-2)
{QQHg--;QQGg[QQHg-1]=(QQGg[QQHg-1]&&QQGg[QQHg]);}else if(QQIg==-4)
{QQHg--;QQGg[QQHg-1]=(QQGg[QQHg-1]||QQGg[QQHg]);}else if(QQIg==-3)
{QQGg[QQHg-1]=(!QQGg[QQHg-1]);}}return QQGg[QQHg-1];}function QQxE(QQGe,QQJg,QQVf,QQKg,QQLg,QQPf,QQQf)
{var QQSf,QQPd,QQMg,QQNg,QQOg,QQPg,QQE,QQQg;var QQRg,QQSg;var QQl=0;var QQk=QQGe.length;var QQFg=[];var QQTg=QQJg.toLowerCase();for(QQl=0;QQl<QQk;QQl++)
{QQPd=QQGe[QQl][0];QQMg=QQGe[QQl][1];QQE=QQGe[QQl][2];QQQg=QQGe[QQl][3];QQRg=QQTg.indexOf(';'+QQPd+'=');if(QQRg>-1)
{QQSg=QQJg.indexOf(';',QQRg+1);if(QQSg>QQRg)
QQPg=unescape(QQJg.substring(QQRg+2+QQPd.length,QQSg));else
QQPg='';if(QQE==5)
QQE=1;if(QQE==1)
QQNg=0;else
QQNg='';if((QQQg==9)||(QQQg==10))
{QQOg=QQMg.split(';');if(QQOg.length==2)
{QQMg=QQOg[0];QQNg=QQOg[1];}else
QQQg=0;}if(QQE==1)
{QQPg=parseFloat(QQPg);QQMg=parseFloat(QQMg);QQNg=parseFloat(QQNg);}if((QQQg>5)&&(QQQg<9))
{if (typeof(QQPg)!='string')
QQPg=QQPg+'';if (typeof(QQMg)!='string')
QQMg=QQMg+'';QQPg=QQPg.toLowerCase();QQMg=QQMg.toLowerCase();}if(QQQg==0)
QQSf=(QQPg==QQMg);else if(QQQg==1)
QQSf=(QQPg!=QQMg);else if(QQQg==2)
QQSf=(QQPg<QQMg);else if(QQQg==3)
QQSf=(QQPg<=QQMg);else if(QQQg==4)
QQSf=(QQPg>QQMg);else if(QQQg==5)
QQSf=(QQPg>=QQMg);else if(QQQg==6)
QQSf=(QQPg.indexOf(QQMg)>-1);else if(QQQg==7)
QQSf=(QQPg.indexOf(QQMg)<0);else if(QQQg==8)
{QQSf=QQPg.substr(0,QQMg.length)==QQMg;}else if(QQQg==9)
{QQSf=((QQPg>=QQMg)&&(QQPg<=QQNg));}else if(QQQg==10)
QQSf=((QQPg<QQMg)||(QQPg>QQNg));}else
{QQSf=false;}if(QQKg==2)
QQFg[QQl]=QQSf;else
{if((QQSf&&(QQKg==1))||(!QQSf&&(QQKg==0)))
QQl=QQk;}}if(QQKg==2)
QQSf=QQwE(QQLg,QQFg);QQSf=QQVf>0?!QQSf:QQSf;if((QQSf?1:0)==QQPf)
return QQPf;QQnE[QQQf]=QQSf;return 2;}function QQyE(QQUg,QQVg)
{var QQJf=new Date();var QQKf=new Date();QQKf.setTime(QQJf-0+parseInt(Ads_T[9],10));var QQWg=QQKf.getHours()*60+QQKf.getMinutes();if(QQUg<QQVg)
QQSf=((QQWg>=QQUg)&&(QQWg<=QQVg));else
QQSf=((QQWg>=QQUg)||(QQWg<=QQVg));return QQSf;}function QQzE(QQXg,QQYg)
{var QQk=QQXg.length;var QQZg;try
{if(typeof(QQXg.Ads_klist)=='string')
QQYg+=QQXg.Ads_klist+'#';}catch(objError) {}for(QQZg=0;QQZg<QQk;QQZg++)
{try
{QQYg=QQzE(QQXg.frames[QQZg],QQYg);}catch(objError) {}}return QQYg;}function QQaF(QQGe,QQE,QQCb,QQRf,QQAh)
{var QQPf=QQGe[0];var QQVf=QQGe[1];var QQSf,QQBh,QQCh,QQDh,QQEh,QQHf,QQFf,QQGf,QQl,QQFh,QQGh,QQHh,QQIh;QQnE=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(QQGe.length==0)
return true;if(((QQPf>0)||(QQE==1))&&!((QQPf==1)&&(QQGe[2]==0)&&(QQGe[3]==1439)))
{QQSf=QQyE(QQGe[2],QQGe[3]);if((QQSf?1:0)==QQPf)
return QQSf;QQnE[0]=QQSf;}QQBh=QQsE(1,QQGe[4],QQCb,(QQE==0)?2:9,QQPf,1,QQRf);if(QQBh<2)
return QQBh==1;if(QQE==0)
{QQBh=QQsE(QQGe[22]&1,IAS[4],Ads_wid,7,QQPf,12,QQRf);if(QQBh<2)
return QQBh==1;QQBh=QQsE(QQGe[22]&2,IAS[6],Ads_nid,8,QQPf,13,QQRf);if(QQBh<2)
return QQBh==1;QQBh=QQuE(QQGe[22]&4,IAS[17],KAS[QQAh][13],12,QQPf,17,QQRf);if(QQBh<2)
return QQBh==1;}QQBh=QQtE(QQGe[6],Ads_T[0],QQVf&1,QQPf,2);if(QQBh<2)
return QQBh==1;QQBh=QQtE(QQGe[7],Ads_T[1],QQVf&2,QQPf,3);if(QQBh<2)
return QQBh==1;QQBh=QQtE(QQGe[8],Ads_T[2],QQVf&4,QQPf,4);if(QQBh<2)
return QQBh==1;QQBh=QQtE(QQGe[9],Ads_T[3],QQVf&8,QQPf,5);if(QQBh<2)
return QQBh==1;QQBh=QQtE(QQGe[26],Ads_T[12],QQVf&1024,QQPf,16);if(QQBh<2)
return QQBh==1;if(QQGe[10].length>1)
{QQSf=((QQGe[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(QQGe[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(QQGe[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(QQGe[10].indexOf('#$14658#')!=-1)) QQSf=true;QQSf=(QQVf&16)>0?!QQSf:QQSf;if((QQSf?1:0)==QQPf)
return QQPf;QQnE[6]=QQSf;}QQBh=QQvE(QQGe[11],QQVf&32,QQPf,false,7);if(QQBh<2)
return QQBh==1;QQBh=QQvE(QQGe[12],QQVf&64,QQPf,true,8);if(QQBh<2)
return QQBh==1;if(QQGe[13].length>0)
{QQBh=QQxE(QQGe[13],';'+Ads_prf+';',QQVf&128,QQGe[15],QQGe[17],QQPf,9);if(QQBh<2)
return QQBh==1;}if(QQGe[14].length>0)
{QQrE();QQBh=QQxE(QQGe[14],QQmE,QQVf&256,QQGe[16],QQGe[18],QQPf,10);if(QQBh<2)
return QQBh==1;}intBwdLevel=0;intBwdTyp=QQGe[27];intBwdUser=QQfF[10];intBwdIP=Ads_T[13];if (intBwdTyp==1){QQbF();intBwdLevel=intBwdUser;}if (intBwdTyp==2){intBwdLevel=intBwdIP;}if (intBwdTyp==3){QQbF();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:(intBwdIP!=0)?intBwdIP:intBwdUser;}if (intBwdTyp==4){QQbF();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((intBwdTyp==5)&&(intBwdUser==intBwdIP))
{ QQbF();intBwdLevel=intBwdIP;}QQBh=QQtE(QQGe[28],intBwdLevel,QQVf&512,QQPf,11);if(QQBh<2)
return QQBh==1;QQIh=QQGe[23];if((QQE==0)&&(QQIh>0))
{QQHf=QQGe[24];if(QQHf.length>2)
QQHf=QQHf.substring(1,QQHf.length-1);QQFf=QQHf.split('#');QQGf=QQFf.length;QQFh=-1;strKList='#'+QQzE(top,'');for(QQl=0;(QQl<QQGf)&&(QQFh<0);QQl++)
{QQGh=(strKList.indexOf('#'+QQFf[QQl]+'#')>-1);if((QQGh?1:4)==QQIh)
QQFh=0;if((QQGh?3:2)==QQIh)
QQFh=1;}if(QQFh<0)
QQFh=((QQIh==1)||(QQIh==4))?1:0;if(QQFh==QQPf)
return (QQFh==1);QQnE[14]=(QQFh==1);}QQl=QQGe[25];if(QQl>0)
{QQGh=IAS[8].indexOf('#'+QQl+':');if(QQGh!=-1)
{QQGh=IAS[8].indexOf(':',QQGh);QQHh=IAS[8].indexOf('#',QQGh);QQGh=IAS[8].substring(QQGh+1,QQHh);QQHh=Ads_fcount[QQl];if(typeOf(QQHh)=='undefined')
QQHh=0;QQSf=QQGh>QQHh;if((QQSf?1:0)==QQPf)
return QQSf;QQnE[15]=QQSf;}}if(QQPf!=2)
return (QQPf==0);else
{return QQwE(QQGe[19],QQnE);}}function QQbF()
{if((QQoE==0)&&QQzA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
QQoE=1;}function QQcF()
{if(QQoE!=1)
return;if(QQbE(1)<6||QQpB)
{if (QQpB||!navigator.javaEnabled())
{QQyD(1,'Start BW-Test','JavaScript');QQoE=3;QQeF();}else
{QQyD(1,'Start BW-Test','Java');document.write('<applet codebase="'+QQjB[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="QQdF"></applet>');QQoE=2;}}else
{QQyD(1,'Start BW-Test','Flash: '+QQbE(1));var QQUc=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(QQKh,QQLh)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(QQKh,QQLh) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQUc+'&path='+QQjB[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQUc+'&path='+QQjB[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');QQoE=2;}}function QQdF(QQJh)
{QQdB=0;QQJh*=8;if(QQJh==0)
QQdB=0;else if(QQJh<9)
QQdB=1;else if(QQJh<33)
QQdB=2;else if(QQJh<65)
QQdB=3;else if(QQJh<129)
QQdB=4;else if(QQJh<385)
QQdB=5;else if(QQJh<769)
QQdB=6;else if(QQJh<1501)
QQdB=7;else if(QQJh<3001)
QQdB=8;else
QQdB=9;QQfD('BNDLVL='+QQdB+QQoD(60*24*7));}function Ads_BWD_DoFSCommand(QQKh,QQLh)
{QQdF(QQLh/8);}function QQeF()
{var QQMh=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('QQcB=new Date();');document.writeln('/'+'/--></scr'+'ipt>');QQkD(QQjB[Ads_sec]+'/dat/dlv/aslprebwd.js?'+QQMh.getTime()+'0');}function Ads_PreBandwidth()
{var QQNh=new Date();var QQOh=Math.round((8026/((QQNh.getTime()-QQcB.getTime()+1)/1000))/1024);QQdF(QQOh);if (QQoE!=3)
QQvC();}