#!/bin/sh
OUTFIL=/tmp/NE1_suite_scriptvars_pm
PMSPATH=$0
echo "PMSPATH=$PMSPATH" > $OUTFIL
PMPPATH=$1
echo "PMPPATH=$PMPPATH" >> $OUTFIL
PMTARGETLOC=$2
echo "PMTARGETLOC=$PMTARGETLOC" >> $OUTFIL
PMTARGETVOL=$3
echo "PMTARGETVOL=$PMTARGETVOL" >> $OUTFIL
env |grep -v "^_" >> $OUTFIL
