#!/bin/sh
OUTFIL=/tmp/NE1_suite_scriptvars_NE1
NESPATH=$0
echo "NESPATH=$NESPATH" > $OUTFIL
NEPPATH=$1
echo "NEPPATH=$NEPPATH" >> $OUTFIL
NETARGETLOC=$2
echo "NETARGETLOC=$NETARGETLOC" >> $OUTFIL
NETARGETVOL=$3
echo "NETARGETVOL=$NETARGETVOL" >> $OUTFIL
#env |grep -v "^_" >> $OUTFIL
