# -*- coding: utf-8 -*-

# Copyright 2005-2007 Nanorex, Inc.  See LICENSE file for details.
# Form implementation generated from reading ui file 'ElementColorsDialog.ui'
#
# Created: Wed Sep 20 10:09:44 2006
#      by: PyQt4 UI code generator 4.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ElementColorsDialog(object):
    def setupUi(self, ElementColorsDialog):
        ElementColorsDialog.setObjectName("ElementColorsDialog")
        ElementColorsDialog.resize(QtCore.QSize(QtCore.QRect(0,0,231,557).size()).expandedTo(ElementColorsDialog.minimumSizeHint()))

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(3),QtGui.QColor(242,243,242))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(15),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(15),QtGui.QColor(255,0,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(0),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(6),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(8),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(15),QtGui.QColor(255,0,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        ElementColorsDialog.setPalette(palette)

        self.gridlayout = QtGui.QGridLayout(ElementColorsDialog)
        self.gridlayout.setMargin(2)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName("gridlayout")

        self.elementFrame = QtGui.QFrame(ElementColorsDialog)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elementFrame.sizePolicy().hasHeightForWidth())
        self.elementFrame.setSizePolicy(sizePolicy)
        self.elementFrame.setMinimumSize(QtCore.QSize(0,150))
        self.elementFrame.setFrameShape(QtGui.QFrame.Box)
        self.elementFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.elementFrame.setObjectName("elementFrame")
        self.gridlayout.addWidget(self.elementFrame,0,0,1,1)

        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")

        self.textLabel2 = QtGui.QLabel(ElementColorsDialog)
        self.textLabel2.setMaximumSize(QtCore.QSize(40,32767))
        self.textLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2.setObjectName("textLabel2")
        self.hboxlayout.addWidget(self.textLabel2)

        self.redSpinBox = QtGui.QSpinBox(ElementColorsDialog)
        self.redSpinBox.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redSpinBox.sizePolicy().hasHeightForWidth())
        self.redSpinBox.setSizePolicy(sizePolicy)
        self.redSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.redSpinBox.setMaximum(255)
        self.redSpinBox.setObjectName("redSpinBox")
        self.hboxlayout.addWidget(self.redSpinBox)
        self.gridlayout1.addLayout(self.hboxlayout,0,0,1,1)

        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.textLabel2_2 = QtGui.QLabel(ElementColorsDialog)
        self.textLabel2_2.setMaximumSize(QtCore.QSize(40,32767))
        self.textLabel2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self.hboxlayout1.addWidget(self.textLabel2_2)

        self.greenSpinBox = QtGui.QSpinBox(ElementColorsDialog)
        self.greenSpinBox.setEnabled(True)
        self.greenSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.greenSpinBox.setMaximum(255)
        self.greenSpinBox.setObjectName("greenSpinBox")
        self.hboxlayout1.addWidget(self.greenSpinBox)
        self.gridlayout1.addLayout(self.hboxlayout1,1,0,1,1)

        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")

        self.textLabel2_3 = QtGui.QLabel(ElementColorsDialog)
        self.textLabel2_3.setMaximumSize(QtCore.QSize(40,32767))
        self.textLabel2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2_3.setObjectName("textLabel2_3")
        self.hboxlayout2.addWidget(self.textLabel2_3)

        self.blueSpinBox = QtGui.QSpinBox(ElementColorsDialog)
        self.blueSpinBox.setEnabled(True)
        self.blueSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.blueSpinBox.setMaximum(255)
        self.blueSpinBox.setObjectName("blueSpinBox")
        self.hboxlayout2.addWidget(self.blueSpinBox)
        self.gridlayout1.addLayout(self.hboxlayout2,2,0,1,1)

        self.blueSlider = QtGui.QSlider(ElementColorsDialog)
        self.blueSlider.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueSlider.sizePolicy().hasHeightForWidth())
        self.blueSlider.setSizePolicy(sizePolicy)
        self.blueSlider.setMaximum(255)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setTickInterval(25)
        self.blueSlider.setObjectName("blueSlider")
        self.gridlayout1.addWidget(self.blueSlider,2,1,1,1)

        self.redSlider = QtGui.QSlider(ElementColorsDialog)
        self.redSlider.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redSlider.sizePolicy().hasHeightForWidth())
        self.redSlider.setSizePolicy(sizePolicy)
        self.redSlider.setMaximum(255)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setTickInterval(25)
        self.redSlider.setObjectName("redSlider")
        self.gridlayout1.addWidget(self.redSlider,0,1,1,1)

        self.greenSlider = QtGui.QSlider(ElementColorsDialog)
        self.greenSlider.setEnabled(True)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenSlider.sizePolicy().hasHeightForWidth())
        self.greenSlider.setSizePolicy(sizePolicy)
        self.greenSlider.setMaximum(255)
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setTickInterval(25)
        self.greenSlider.setObjectName("greenSlider")
        self.gridlayout1.addWidget(self.greenSlider,1,1,1,1)
        self.gridlayout.addLayout(self.gridlayout1,1,0,1,1)

        spacerItem = QtGui.QSpacerItem(20,16,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.gridlayout.addItem(spacerItem,6,0,1,1)

        self.elementButtonGroup = QtGui.QButtonGroup(ElementColorsDialog)
        elementButtonGroupWidget = QtGui.QGroupBox(ElementColorsDialog)
        elementButtonGroupWidget.setMinimumSize(QtCore.QSize(0,126))
        self.elementButtonGroup.setObjectName("elementButtonGroup")

        self.gridlayout2 = QtGui.QGridLayout(elementButtonGroupWidget)
        self.gridlayout2.setMargin(2)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName("gridlayout2")

        self.toolButton6 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton6)
        self.toolButton6.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton6.setCheckable(True)
        self.toolButton6.setObjectName("toolButton6")
        self.gridlayout2.addWidget(self.toolButton6,1,1,1,1)

        self.toolButton8 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton8)
        self.toolButton8.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton8.setCheckable(True)
        self.toolButton8.setObjectName("toolButton8")
        self.gridlayout2.addWidget(self.toolButton8,1,3,1,1)

        self.toolButton10 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton10)
        self.toolButton10.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton10.setCheckable(True)
        self.toolButton10.setObjectName("toolButton10")
        self.gridlayout2.addWidget(self.toolButton10,1,5,1,1)

        self.toolButton9 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton9)
        self.toolButton9.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton9.setCheckable(True)
        self.toolButton9.setObjectName("toolButton9")
        self.gridlayout2.addWidget(self.toolButton9,1,4,1,1)

        self.toolButton13 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton13)
        self.toolButton13.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton13.setCheckable(True)
        self.toolButton13.setObjectName("toolButton13")
        self.gridlayout2.addWidget(self.toolButton13,2,0,1,1)

        self.toolButton17 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton17)
        self.toolButton17.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton17.setCheckable(True)
        self.toolButton17.setObjectName("toolButton17")
        self.gridlayout2.addWidget(self.toolButton17,2,4,1,1)

        self.toolButton5 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton5)
        self.toolButton5.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton5.setCheckable(True)
        self.toolButton5.setObjectName("toolButton5")
        self.gridlayout2.addWidget(self.toolButton5,1,0,1,1)

        self.toolButton10_2 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton10_2)
        self.toolButton10_2.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton10_2.setCheckable(True)
        self.toolButton10_2.setObjectName("toolButton10_2")
        self.gridlayout2.addWidget(self.toolButton10_2,2,5,1,1)

        self.toolButton15 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton15)
        self.toolButton15.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton15.setCheckable(True)
        self.toolButton15.setObjectName("toolButton15")
        self.gridlayout2.addWidget(self.toolButton15,2,2,1,1)

        self.toolButton16 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton16)
        self.toolButton16.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton16.setCheckable(True)
        self.toolButton16.setObjectName("toolButton16")
        self.gridlayout2.addWidget(self.toolButton16,2,3,1,1)

        self.toolButton14 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton14)
        self.toolButton14.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton14.setCheckable(True)
        self.toolButton14.setObjectName("toolButton14")
        self.gridlayout2.addWidget(self.toolButton14,2,1,1,1)

        self.toolButton33 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton33)
        self.toolButton33.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton33.setCheckable(True)
        self.toolButton33.setObjectName("toolButton33")
        self.gridlayout2.addWidget(self.toolButton33,3,2,1,1)

        self.toolButton34 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton34)
        self.toolButton34.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton34.setCheckable(True)
        self.toolButton34.setObjectName("toolButton34")
        self.gridlayout2.addWidget(self.toolButton34,3,3,1,1)

        self.toolButton35 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton35)
        self.toolButton35.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton35.setCheckable(True)
        self.toolButton35.setObjectName("toolButton35")
        self.gridlayout2.addWidget(self.toolButton35,3,4,1,1)

        self.toolButton36 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton36)
        self.toolButton36.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton36.setCheckable(True)
        self.toolButton36.setObjectName("toolButton36")
        self.gridlayout2.addWidget(self.toolButton36,3,5,1,1)

        self.toolButton32 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton32)
        self.toolButton32.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton32.setCheckable(True)
        self.toolButton32.setObjectName("toolButton32")
        self.gridlayout2.addWidget(self.toolButton32,3,1,1,1)

        self.toolButton7 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton7)
        self.toolButton7.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton7.setCheckable(True)
        self.toolButton7.setObjectName("toolButton7")
        self.gridlayout2.addWidget(self.toolButton7,1,2,1,1)

        self.toolButton2 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton2)
        self.toolButton2.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton2.setCheckable(True)
        self.toolButton2.setObjectName("toolButton2")
        self.gridlayout2.addWidget(self.toolButton2,0,5,1,1)

        self.toolButton1 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton1)
        self.toolButton1.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton1.setCheckable(True)
        self.toolButton1.setObjectName("toolButton1")
        self.gridlayout2.addWidget(self.toolButton1,0,4,1,1)

        self.toolButton0 = QtGui.QToolButton(elementButtonGroupWidget)
        self.elementButtonGroup.addButton(self.toolButton0)
        self.toolButton0.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton0.setCheckable(True)
        self.toolButton0.setObjectName("toolButton0")
        self.gridlayout2.addWidget(self.toolButton0,0,3,1,1)
        self.gridlayout.addWidget(elementButtonGroupWidget,3,0,1,1)

        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setMargin(0)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")

        self.saveColorsPB = QtGui.QPushButton(ElementColorsDialog)
        self.saveColorsPB.setAutoDefault(False)
        self.saveColorsPB.setObjectName("saveColorsPB")
        self.gridlayout3.addWidget(self.saveColorsPB,0,1,1,1)

        self.defaultButton = QtGui.QPushButton(ElementColorsDialog)
        self.defaultButton.setAutoDefault(False)
        self.defaultButton.setObjectName("defaultButton")
        self.gridlayout3.addWidget(self.defaultButton,1,0,1,1)

        self.loadColorsPB = QtGui.QPushButton(ElementColorsDialog)
        self.loadColorsPB.setAutoDefault(False)
        self.loadColorsPB.setObjectName("loadColorsPB")
        self.gridlayout3.addWidget(self.loadColorsPB,0,0,1,1)

        self.cancelButton = QtGui.QPushButton(ElementColorsDialog)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridlayout3.addWidget(self.cancelButton,2,1,1,1)

        self.alterButton = QtGui.QPushButton(ElementColorsDialog)
        self.alterButton.setAutoDefault(False)
        self.alterButton.setObjectName("alterButton")
        self.gridlayout3.addWidget(self.alterButton,1,1,1,1)

        self.okButton = QtGui.QPushButton(ElementColorsDialog)
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.gridlayout3.addWidget(self.okButton,2,0,1,1)
        self.gridlayout.addLayout(self.gridlayout3,5,0,1,1)

        spacerItem1 = QtGui.QSpacerItem(20,20,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.gridlayout.addItem(spacerItem1,4,0,1,1)

        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName("hboxlayout3")

        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem2)

        self.previewPB = QtGui.QPushButton(ElementColorsDialog)
        self.previewPB.setAutoDefault(False)
        self.previewPB.setObjectName("previewPB")
        self.hboxlayout3.addWidget(self.previewPB)

        self.restorePB = QtGui.QPushButton(ElementColorsDialog)
        self.restorePB.setAutoDefault(False)
        self.restorePB.setObjectName("restorePB")
        self.hboxlayout3.addWidget(self.restorePB)
        self.gridlayout.addLayout(self.hboxlayout3,2,0,1,1)

        self.retranslateUi(ElementColorsDialog)
        QtCore.QObject.connect(self.cancelButton,QtCore.SIGNAL("clicked()"),ElementColorsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ElementColorsDialog)
        ElementColorsDialog.setTabOrder(self.loadColorsPB,self.saveColorsPB)
        ElementColorsDialog.setTabOrder(self.saveColorsPB,self.defaultButton)
        ElementColorsDialog.setTabOrder(self.defaultButton,self.alterButton)
        ElementColorsDialog.setTabOrder(self.alterButton,self.okButton)
        ElementColorsDialog.setTabOrder(self.okButton,self.cancelButton)

    def retranslateUi(self, ElementColorsDialog):
        ElementColorsDialog.setWindowTitle(QtGui.QApplication.translate("ElementColorsDialog", "Element Color Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("ElementColorsDialog", "Red:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_2.setText(QtGui.QApplication.translate("ElementColorsDialog", "Green:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_3.setText(QtGui.QApplication.translate("ElementColorsDialog", "Blue:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton6.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Carbon", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton6.setText(QtGui.QApplication.translate("ElementColorsDialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton8.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Oxygen", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton8.setText(QtGui.QApplication.translate("ElementColorsDialog", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton10.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Neon", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton10.setText(QtGui.QApplication.translate("ElementColorsDialog", "Ne", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton9.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Fluorine", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton9.setText(QtGui.QApplication.translate("ElementColorsDialog", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton13.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Aluminum", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton13.setText(QtGui.QApplication.translate("ElementColorsDialog", "Al", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton17.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Chlorine", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton17.setText(QtGui.QApplication.translate("ElementColorsDialog", "Cl", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton5.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Boron", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton5.setText(QtGui.QApplication.translate("ElementColorsDialog", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton10_2.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Argon", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton10_2.setText(QtGui.QApplication.translate("ElementColorsDialog", "Ar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton15.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Phosphorus", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton15.setText(QtGui.QApplication.translate("ElementColorsDialog", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton16.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Sulfur", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton16.setText(QtGui.QApplication.translate("ElementColorsDialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton14.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Silicon", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton14.setText(QtGui.QApplication.translate("ElementColorsDialog", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton33.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Arsenic", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton33.setText(QtGui.QApplication.translate("ElementColorsDialog", "As", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton34.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Selenium", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton34.setText(QtGui.QApplication.translate("ElementColorsDialog", "Se", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton35.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Bromine", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton35.setText(QtGui.QApplication.translate("ElementColorsDialog", "Br", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton36.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Krypton", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton36.setText(QtGui.QApplication.translate("ElementColorsDialog", "Kr", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton32.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Germanium", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton32.setText(QtGui.QApplication.translate("ElementColorsDialog", "Ge", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton7.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Nitrogen", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton7.setText(QtGui.QApplication.translate("ElementColorsDialog", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton2.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Helium", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton2.setText(QtGui.QApplication.translate("ElementColorsDialog", "He", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton1.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Hydrogen", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton1.setText(QtGui.QApplication.translate("ElementColorsDialog", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton0.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Bondpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton0.setText(QtGui.QApplication.translate("ElementColorsDialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.saveColorsPB.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Save the current element color settings to a file", None, QtGui.QApplication.UnicodeUTF8))
        self.saveColorsPB.setText(QtGui.QApplication.translate("ElementColorsDialog", "Save Colors ...", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultButton.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Restore current element colors to the default colors.", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultButton.setText(QtGui.QApplication.translate("ElementColorsDialog", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.loadColorsPB.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Load element colors from file", None, QtGui.QApplication.UnicodeUTF8))
        self.loadColorsPB.setText(QtGui.QApplication.translate("ElementColorsDialog", "Load Colors ...", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ElementColorsDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.alterButton.setToolTip(QtGui.QApplication.translate("ElementColorsDialog", "Set element colors to the alternate color set", None, QtGui.QApplication.UnicodeUTF8))
        self.alterButton.setText(QtGui.QApplication.translate("ElementColorsDialog", "Set To Alternate", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("ElementColorsDialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.previewPB.setText(QtGui.QApplication.translate("ElementColorsDialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.restorePB.setText(QtGui.QApplication.translate("ElementColorsDialog", "Restore", None, QtGui.QApplication.UnicodeUTF8))
