# Copyright 2008 Nanorex, Inc.  See LICENSE file for details.
"""
NE1_Build_Constants.py is intended to be a very small file which consists
of only the data that is likely to change for any given release, including
anything which might be changed (manually or automatically) during the
process of building a release itself.

None other than system imports should be used without good reason.

@note: This file is updated by the NE1 installer build scripts.
       Do not edit this file manually.

@version: $Id$
@copyright: 2008 Nanorex, Inc.  See LICENSE file for details.
"""

NE1_RELEASE_VERSION = "1.1.1"
NE1_RELEASE_DATE = "August 11, 2008"
NE1_OFFICIAL_RELEASE_CANDIDATE = 0
NE1_USE_bsddb3 = False
NE1_CONSOLE_REDIRECT = False
