# Copyright 2004-2007 Nanorex, Inc.  See LICENSE file for details. 
"""
SelectAtoms_Command.py 

The 'Command' part of the SelectAtoms Mode (SelectAtoms_basicCommand and 
SelectAtoms_basicGraphicsMode are the two split classes of the old 
selectAtomsMode)  It provides the command object for its GraphicsMode class. 
The Command class defines anything related to the 'command half' of the mode -- 
For example: 
- Anything related to its current Property Manager, its settings or state
- The model operations the command does (unless those are so simple
  that the mouse event bindings in the _GM half can do them directly
  and the code is still clean, *and* no command-half subclass needs
  to override them).

@version: $Id$
@copyright: 2004-2007 Nanorex, Inc.  See LICENSE file for details.


TODO:
- Items mentioned in Select_GraphicsMode.py 
- Other items listed in Select_Command.py

History:
Ninad & Bruce 2007-12-13: Created new Command and GraphicsMode classes from 
                          the old class selectAtomsMode and moved the 
                          Command related methods into this class from 
                          selectAtomsMode.py

"""
import platform
from runSim import LocalMinimize_function
from debug import print_compact_traceback

from Select_Command import Select_basicCommand
from GraphicsMode_API import GraphicsMode_API
from SelectAtoms_GraphicsMode import SelectAtoms_GraphicsMode

class SelectAtoms_basicCommand(Select_basicCommand):
    """
    SelectAtoms_basicCommand
    The 'Command' part of the SelectAtoms Mode (SelectAtoms_basicCommand and 
    SelectAtoms_basicGraphicsMode are the two split classes of the old 
    selectAtomsMode)  It provides the command object for its GraphicsMode class. 
    The Command class defines anything related to the 'command half' of the 
    mode -- 
    For example: 
    - Anything related to its current Property Manager, its settings or state
    - The model operations the command does (unless those are so simple
      that the mouse event bindings in the _GM half can do them directly
      and the code is still clean, *and* no command-half subclass needs
      to override them).
    """
    commandName = 'SELECTATOMS'
    default_mode_status_text = "Mode: Select Atoms"
    featurename = "Select Atoms Mode"
    
    # Don't highlight singlets in selectAtomsMode. Fixes bug 1540.mark 060220.
    highlight_singlets = False         
    water_enabled = False # Fixes bug 1583. mark 060301.
    
    def Enter(self): 
        Select_basicCommand.Enter(self)        
        self.o.assy.permit_pick_atoms()
        self.w.win_update()
            #k needed? I doubt it, I bet caller of Enter does it
            # [bruce comment 050517]

        # Reinitialize previously picked atoms (ppas).
        self.o.assy.ppa2 = self.o.assy.ppa3 = None

        self.o.selatom = None
        self.graphicsMode.reset_drag_vars()
        self.dont_update_gui = True # until changed in init_gui
        self.graphicsMode.ignore_next_leftUp_event = False
            # Set to True in leftDouble() and checked by the left*Up()
            # event handlers to determine whether they should ignore the
            # (second) left*Up event generated by the second LMB up/release
            # event in a double click.
            
    
    call_makeMenus_for_each_event = True     
    
    def makeMenus(self): 
        selatom, selobj = self.graphicsMode.update_selatom_and_selobj(None)

        self.Menu_spec = []

        # Local minimize [now called Adjust Atoms in history/Undo,
        #Adjust <what> here and in selectMode -- mark & bruce 060705]
        # WARNING: This code is duplicated in depositMode.makeMenus(). 
        #--mark 060314.
        if selatom is not None and \
           not selatom.is_singlet() and \
           self.w.simSetupAction.isEnabled():
            
            # see comments in depositMode version
            self.Menu_spec.append((
                'Adjust atom %s' % selatom, 
                lambda e1=None,a=selatom: self.localmin(a,0) ))
            
            self.Menu_spec.append((
                'Adjust 1 layer', 
                lambda e1=None,a=selatom: self.localmin(a,1) ))
            
            self.Menu_spec.append((
                'Adjust 2 layers', 
                lambda e1=None,a=selatom: self.localmin(a,2) ))

        # selobj-specific menu items. [revised by bruce 060405; 
        #for more info see the same code in depositMode]
        if selobj is not None and hasattr(selobj, 'make_selobj_cmenu_items'):
            try:
                selobj.make_selobj_cmenu_items(self.Menu_spec)
            except:
                print_compact_traceback("bug: exception (ignored) in"
                                        " make_selobj_cmenu_items "
                                        "for %r: " % selobj)

        # separator and other mode menu items.
        if self.Menu_spec:
            self.Menu_spec.append(None)

        # Enable/Disable Jig Selection.
        # This is duplicated in depositMode.makeMenus() and 
        #selectMolsMode.makeMenus().
        if self.o.jigSelectionEnabled:
            self.Menu_spec.extend( [('Enable Jig Selection',  
                                     self.graphicsMode.toggleJigSelection, 
                                     'checked')])
        else:
            self.Menu_spec.extend( [('Enable Jig Selection', 
                                     self.graphicsMode.toggleJigSelection, 
                                     'unchecked')])

        self.Menu_spec.extend( [
            # mark 060303. added the following:
            None,
            ('Change Background Color...', self.w.changeBackgroundColor),
        ])

        return # from makeMenus
    
    # Local minimize [now called Adjust Atoms in history/Undo, Adjust <what> 
    #in menu commands -- mark & bruce 060705]
    def localmin(self, atom, nlayers): #bruce 051207 #e might generalize to 
                                       #take a list or pair of atoms, other 
                                       #options
        if platform.atom_debug:
            print "debug: reloading runSim on each use, for development"\
                  "[localmin %s, %d]" % (atom, nlayers)
            import runSim, debug
            debug.reload_once_per_event(runSim) #bruce 060705 revised this
        if 1:
            # this does not work, 
            #I don't know why, should fix sometime: [bruce 060705]
            self.set_cmdname("Adjust Atoms") # for Undo (should we be more 
                                             #specific, like the menu text was? 
                                             #why didn't that get used?)
        
        LocalMinimize_function( [atom], nlayers )
        return


class SelectAtoms_Command(SelectAtoms_basicCommand):
    """
    SelectAtoms_Command  
    @see: B{SelectAtoms_basicCommand}
    @see: splitting_a_mode.py
    """
    GraphicsMode_class = SelectAtoms_GraphicsMode
    
    def __init__(self, commandSequencer):
        SelectAtoms_basicCommand.__init__(self, commandSequencer)
        self._create_GraphicsMode()
        self._post_init_modify_GraphicsMode()
        return
        
    def _create_GraphicsMode(self):
        GM_class = self.GraphicsMode_class
        assert issubclass(GM_class, GraphicsMode_API)
        args = [self] 
        kws = {} 
        self.graphicsMode = GM_class(*args, **kws)

    def _post_init_modify_GraphicsMode(self):
        pass
    
