# Copyright 2007 Nanorex, Inc.  See LICENSE file for details. 
"""
packageData.py -- data about modules and packages, for use by PackageDependency.py

@author: Eric M
@version: $Id$
@copyright: 2007 Nanorex, Inc.  See LICENSE file for details.
"""

packageColors = {
    "ui"          : "#8050ff",
    "PM"          : "#8070ff",
    "graphics"    : "#80a0ff",

    "model"       : "#80ff50",
    "foundation"  : "#80ff70",
    "exprs"       : "#80ffa0",

    "io"          : "#ffff80",
    "utilities"   : "#ffa080",

    "examples"    : "#ff3030",
    "test"        : "#ff3060",
    "top"         : "#ff3090",
    }

packageLevels = {
    "top"         : 7,
    "test"        : 7,
    "examples"    : 7,
    "ui"          : 6,
    "PM"          : 6,
    "io"          : 5,
    "model"       : 4,
    "graphics"    : 4,
    "foundation"  : 3,
    "exprs"       : 3,
    "geometry"    : 3,
    "utilities"   : 2,
    "platform"    : 1,
    }

packageMapping = {
    "assembly"                     : "model",
    "AtomGeneratorPropertyManager" : "ui",
    "AtomGenerator"                : "ui",
    "atomtypes"                    : "model",
    "bond_constants"               : "model",
    "bond_drawer"                  : "graphics",
    "bonds_from_atoms"             : "model",
    "bonds"                        : "model",
    "bond_chains"                  : "model",
    "bond_updater"                 : "model",
    "bond_utils"                   : "model",
    "BuildAtomsPropertyManager"    : "ui",
    "build_utils"                  : "ui",
    "changes"                      : "foundation",
    "chem_patterns"                : "model",
    "chem"                         : "model",
    "ChunkPropDialog"              : "ui",
    "ChunkProp"                    : "ui",
    "chunk"                        : "model",
    "CmdMgr_Constants"             : "ui",
    "CommandManager"               : "ui",
    "Command"                      : "ui",
    "CommentPropDialog"            : "ui",
    "CommentProp"                  : "ui",
    "Comment"                      : "model",
    "confirmation_corner"          : "ui",
    "constants"                    : "utilities",
    "CoNTubGenerator"              : "ui",
    "CookieCtrlPanel"              : "ui",
    "cookieMode"                   : "ui",
    "CookiePropertyManager"        : "ui",
    "crossovers"                   : "model",
    "cursors"                      : "ui",
    "CylinderChunks"               : "graphics",
    "DebugMenuMixin"               : "ui",
    "debug_prefs"                  : "utilities",
    "debug"                        : "utilities",
    "depositMode"                  : "ui",
    "dimensions"                   : "graphics",
    "DirectionArrow"               : "ui",
    "displaymodes"                 : "ui",
    "Dna_Constants"                : "model",
    "DnaGeneratorPropertyManager"  : "ui",
    "DnaGenerator"                 : "ui",
    "Dna"                          : "model",
    "DragHandler"                  : "ui",
    "draw_bond_vanes"              : "graphics",
    "drawer"                       : "graphics",
    "DynamicTip"                   : "ui",
    "EditController_PM"            : "ui",
    "EditController"               : "ui",
    "ElementColorsDialog"          : "ui",
    "elementColors"                : "ui",
    "ElementSelectorDialog"        : "ui",
    "elementSelector"              : "ui",
    "elements"                     : "model",
    "EndUser"                      : "utilities",
    "env"                          : "utilities",
    "ESPImagePropDialog"           : "ui",
    "ESPImageProp"                 : "ui",
    "example_expr_command"         : "examples",
    "extensions"                   : "top_level",
    "extrudeMode"                  : "ui",
    "ExtrudePropertyManager"       : "ui",
    "fileIO"                       : "io",
    "files_gms"                    : "io",
    "files_mmp"                    : "io",
    "files_nh"                     : "io",
    "files_pdb"                    : "io",
    "fusechunksMode"               : "ui",
    "FusePropertyManager"          : "ui",
    "GamessJob"                    : "io",
    "GamessPropDialog"             : "ui",
    "GamessProp"                   : "ui",
    "GeneratorBaseClass"           : "ui",
    "generator_button_images"      : "ui",
    "GeneratorController"          : "ui",
    "geometry"                     : "geometry",
    "GlobalPreferences"            : "utilities",
    "GLPane_minimal"               : "graphics",
    "GLPane"                       : "graphics",
    "gpl_only"                     : "platform",
    "GrapheneGeneratorPropertyManager"
                                   : "ui",
    "GrapheneGenerator"            : "ui",
    "GraphicsMode"                 : "ui",
    "GridPlanePropDialog"          : "ui",
    "GridPlaneProp"                : "ui",
    "GROMACS"                      : "io",
    "Group"                        : "foundation", # some model code?
    "GroupButtonMixin"             : "ui",
    "GroupPropDialog"              : "ui",
    "GroupProp"                    : "ui",
    "handles"                      : "ui",
    "HelpDialog"                   : "ui",
    "help"                         : "ui",
    "HistoryWidget"                : "ui",
    "icon_utilities"               : "io",
    "ImageUtils"                   : "io",
    "_import_roots"                : "top_level",
    "Initialize"                   : "utilities",
    "inval"                        : "foundation",
    "jig_Gamess"                   : "model",
    "JigPropDialog"                : "ui",
    "JigProp"                      : "ui",
    "jigs_measurements"            : "model",
    "jigs_motors"                  : "model",
    "jigs_planes"                  : "model",
    "jigs"                         : "model",
    "JobManagerDialog"             : "ui",
    "JobManager"                   : "ui",
    "LinearMotorEditController"    : "ui",
    "LinearMotorPropertyManager"   : "ui",
    "Line"                         : "ui", # geometry, model?
    "main"                         : "top_level",
    "MainWindowUI"                 : "ui",
    "mdldata"                      : "io",
    "MinimizeEnergyPropDialog"     : "ui",
    "MinimizeEnergyProp"           : "ui",
    "modelTreeGui"                 : "ui",
    "modelTree"                    : "ui",
    "CommandSequencer"             : "ui",
    "modes"                        : "ui",
    "modifyMode"                   : "ui",
    "MotorPropertyManager"         : "ui",
    "MovePropertyManager"          : "ui",
    "moviefile"                    : "io",
    "movieMode"                    : "ui",
    "MoviePropertyManager"         : "ui",
    "movie"                        : "ui", # mixture of stuff
    "MWsemantics"                  : "ui",
    "NanoHiveDialog"               : "ui",
    "NanoHive"                     : "ui",
    "NanoHiveUtils"                : "io",
    "NanotubeGeneratorPropertyManager"
                                   : "ui",
    "NanotubeGenerator"            : "ui",
    "NE1ToolBar"                   : "ui",
    "node_indices"                 : "foundation",
    "ops_atoms"                    : "model",
    "ops_connected"                : "model",
    "ops_copy"                     : "model", # parts may be foundation
    "op_select_doubly"             : "model",
    "ops_files"                    : "io",
    "ops_motion"                   : "model",
    "ops_rechunk"                  : "model",
    "ops_select"                   : "model",
    "ops_view"                     : "ui", # parts may be graphics
    "PanMode"                      : "ui",
    "ParameterDialog"              : "ui",
    "parse_utils"                  : "io",
    "PartLibPropertyManager"       : "ui",
    "PartLibraryMode"              : "ui",
    "PartPropDialog"               : "ui",
    "PartProp"                     : "ui",
    "part"                         : "foundation", # model, graphics?
    "PasteMode"                    : "ui",
    "PastePropertyManager"         : "ui",
    "pi_bond_sp_chain"             : "model",
    "PlaneEditController"          : "ui",
    "PlanePropertyManager"         : "ui",
    "Plane"                        : "ui", # geometry, model?
    "PlatformDependent"            : "platform",
    "platform"                     : "utilities",
    "PlotToolDialog"               : "ui",
    "PlotTool"                     : "ui",
    "povheader"                    : "io",
    "povray"                       : "io",
    "PovrayScenePropDialog"        : "ui",
    "PovraySceneProp"              : "ui",
    "PovrayScene"                  : "model", # ?
    "preferences"                  : "utilities",
    "prefs_constants"              : "utilities",
    "prefsTree"                    : "ui",
    "prefs_widgets"                : "ui",
    "Process"                      : "io",
    "PropMgr_Constants"            : "PM",
    "pyrex_test"                   : "top_level",
    "qt4transition"                : "utilities",
    "qutemol"                      : "io",
    "ReferenceGeometry"            : "ui", # geometry, model?
    "reposition_baggage"           : "model",
    "RotaryMotorEditController"    : "ui",
    "RotaryMotorPropertyManager"   : "ui",
    "RotateMode"                   : "ui",
    "runSim"                       : "io",
    "selectAtomsMode"              : "ui",
    "selectMode"                   : "ui",
    "selectMolsMode"               : "ui",
    "Selobj"                       : "ui", # graphics?
    "ServerManagerDialog"          : "ui",
    "ServerManager"                : "ui",
    "setup2"                       : "tools",
    "setup"                        : "tools",
    "shape"                        : "ui", # geometry, graphics?
    "SimJob"                       : "io",
    "SimServer"                    : "io",
    "SimSetupDialog"               : "ui",
    "SimSetup"                     : "ui",
    "Sponsors"                     : "ui",
    "state_constants"              : "foundation",
    "state_utils"                  : "foundation",
    "state_utils_unset"            : "foundation",
    "StatPropDialog"               : "ui",
    "StatProp"                     : "ui",
    "StatusBar"                    : "ui",
    "SurfaceChunks"                : "geometry",
    "TemporaryCommand"             : "ui",
    "test_command_PMs"             : "test",
    "test_commands"                : "test",
    "test_connectWithState_constants"
                                   : "test",
    "test_connectWithState_PM"     : "test",
    "test_connectWithState"        : "test",
    "testdraw"                     : "test",
    "testmode"                     : "test",
    "ThermoPropDialog"             : "ui",
    "ThermoProp"                   : "ui",
    "ThumbView"                    : "graphics",
    "Ui_BuildAtomsPropertyManager" : "ui",
    "Ui_BuildStructuresMenu"       : "ui",
    "Ui_BuildStructuresToolBar"    : "ui",
    "Ui_BuildToolsMenu"            : "ui",
    "Ui_BuildToolsToolBar"         : "ui",
    "Ui_CommandManager"            : "ui",
    "Ui_CookiePropertyManager"     : "ui",
    "Ui_DimensionsMenu"            : "ui",
    "Ui_EditMenu"                  : "ui",
    "Ui_ExtrudePropertyManager"    : "ui",
    "Ui_FileMenu"                  : "ui",
    "Ui_HelpMenu"                  : "ui",
    "Ui_InsertMenu"                : "ui",
    "Ui_MovePropertyManager"       : "ui",
    "Ui_MoviePropertyManager"      : "ui",
    "Ui_PartWindow"                : "ui",
    "Ui_SelectMenu"                : "ui",
    "Ui_SelectToolBar"             : "ui",
    "Ui_SimulationMenu"            : "ui",
    "Ui_SimulationToolBar"         : "ui",
    "Ui_StandardToolBar"           : "ui",
    "Ui_ToolsMenu"                 : "ui",
    "Ui_ViewMenu"                  : "ui",
    "Ui_ViewOrientation"           : "ui",
    "Ui_ViewToolBar"               : "ui",
    "undo_archive"                 : "foundation",
    "undo_manager"                 : "foundation",
    "undo"                         : "foundation",
    "UserPrefsDialog"              : "ui",
    "UserPrefs"                    : "ui",
    "Utility"                      : "foundation", # some model code?
    "version"                      : "utilities",
    "ViewOrientationWindow"        : "ui",
    "VQT"                          : "geometry",
    "whatsthis"                    : "ui",
    "widget_controllers"           : "ui",
    "widgets"                      : "ui",
    "wiki_help"                    : "ui", # some io?
    "ZoomMode"                     : "ui",
    }

# end
